### ISSUE TITLE
Capture data and send to a partial?

### ISSUE THREAD

**Issue by willemmulder** [eta-dev/eta#10]
If I had a template 'somepage.html' then I'd like to point to a 'layout' (which is a template itself with header, footer etc that renders out a passed body somewhere) and then pass/inject a body into it. Like how e.g. Jekyll works.  Something along the lines of:

<% var body = %>
lots of HTML
<% ; %>
<%~ E.include('layout', {body: body}) %>

Is that possible?

**Comment by nebrelbug** [comment]
@willemmulder actually, that's completely possible, but I'd never thought about that before!

Here's a quick demo I put up (it's slightly more complex than the example you gave, and allows passing partial data):

```js
// index.js
var eta = require("eta")

eta.renderFile("./template.eta", { name: "Ben" }, function (err, rendered) {
  console.log(rendered)
})
```

```ejs
<%/* template.eta */%>

<% var body = (it)=>{var tR="" %>

Hi, this is the body template

<h1><%= it.title %></h1>

<% return tR } %>

<%~ E.includeFile('./layout.eta', {body: body}) %>
```

```ejs
<%/* layout.eta */%>

This is the body
================

<%~ it.body({title: "Awesome Title"}) %>
```

Running `node index.js` returns the following output:
> This is the body
> \================
>
>
> Hi, this is the body template
>
> \<h1>Awesome Title\</h1>

**Comment by nebrelbug** [comment]
The important part is

```ejs
<% var body = (it)=>{var tR="" %>

Hi, this is the body template

<h1><%= it.title %></h1>

<% return tR } %>
```

Note that you have to unescape `<%~ it.body({title: "Awesome Title"}) %>` and `<%~ E.includeFile('./layout.eta', {body: body}) %>` if you want HTML inside either.

**Comment by nebrelbug** [comment]
Hmm... it would be really easy to create a plugin that used `{@` as a shorthand for `(it)=>{var tR=""` and `@}` as a shorthand for `return tR`, so it would look like this instead:

```ejs
<% var body = {@ %>

Hi, this is the body template

<h1><%= it.title %></h1>

<% @} %>
```

**Comment by willemmulder** [comment]
> The important part is
> 
> ```
> <% var body = (it)=>{var tR="" %>
> 
> Hi, this is the body template
> 
> <h1><%= it.title %></h1>
> 
> <% return tR } %>
> ```
> 
> Note that you have to unescape `<%~ it.body({title: "Awesome Title"}) %>` and `<%~ E.includeFile('./layout.eta', {body: body}) %>` if you want HTML inside either.

Thanks! Compared to my original example, what I don't understand is why I'd need to put `var tR=""`. How does that cause the rest of the HTML to be added into that variable as well? How does that work under the hood?

**Comment by nebrelbug** [comment]
@willemmulder Under the hood, Eta compiles this:

```ejs
Hi, this is the body template

<h1><%= it.title %></h1>
```

into roughly this (inside a function which is called with `it` as the data object):

```js
tR+='Hi, this is the body template\n\n<h1>'
tR+=E.e(it.title) // Eta automatically XML-escapes references
tR+='</h1>'
```

It uses `tR` as the output variable by default. What I did above is just wrap it in a function, so it compiles to this:
 
```js
var body = (it)=>{var tR=""
tR+='\nHi, this is the body template\n\n<h1>'
tR+=E.e(it.title)
tR+='</h1>\n\n'
return tR }
```

Because of the rules of JavaScript closures, `tR` is "shadowed" as an empty string inside the function.

Did I explain that well?

**Comment by willemmulder** [comment]
Yep, that makes sense to me, thanks! 

We define tR ourselves so it becomes a function-local variable. Then eta will auto-add everything into that tR variable. And finally, we return everything that's in tR into the body variable.

Then, we can call `body` whenever we like and it renders appropriately.

Having the shorthand {@ for that would be great though! That's not only easier, but I also think that people should not have to be bothered with understanding the tR variable, or other 'under-the-hood' magic 👍

**Comment by nebrelbug** [comment]
@willemmulder

> We define tR ourselves so it becomes a function-local variable. Then eta will auto-add everything into that tR variable. And finally, we return everything that's in tR to the caller of the body function.
>
> Then, we can call body whenever we like and it renders appropriately.

Exactly correct.

> Having the shorthand {@ for that would be great though! That's not only easier, but I also think that people should not have to be bothered with understanding the tR variable, or other 'under-the-hood' magic :+1:

Hmm, I think I might create a plugin that will handle this and layouts. I'd probably include it in the `eta` repo so user's didn't have to bundle anything extra.

**Comment by willemmulder** [comment]
@nebrelbug That would be fantastic! 👍

**Comment by nebrelbug** [comment]
@willemmulder I'm working on this now BTW :rocket: 

I've decided to build in simple layout support. My current results have that only adding about ~60 bytes to the bundle size.

I'll also release a `macros` plugin (which will allow `{@` and `@}`) and probably a template inheritance plugin :)

**Comment by willemmulder** [comment]
Nice one! Let me know once I can test something 👍

**Comment by nebrelbug** [comment]
@willemmulder just released https://github.com/eta-dev/eta/releases/tag/v1.9.0 with layouts support!

I hope to release a plugin macro sometime early next week.

**Comment by willemmulder** [comment]
Great work!

Two suggestions:

1. (unrelated ;-)) The benchmark page seems to be broken for me https://ghcdn.rawgit.org/eta-dev/eta/master/browser-tests/benchmark.html

2. It would be great if we would be able to pass things to the layout file, so it can e.g. render a title in the head, or highlight the active page in the menu. In Jekyll, we'd usually use the 'front matter' for that, but here I'd suggest we can simply pass variables like 

```js
<% layout("./my-layout.eta",{"activePage": "Products"}) %>
```

And then in eta we do something like `Object.assign({body:tR},passedParams)` to pass to the includeFile function.

Would that make sense?

**Comment by nebrelbug** [comment]
Sorry about the benchmark page! The script linking to Eta broke because I removed the `dist/` folder from Git. I fixed this in the last release, but you'll probably need to hard reload to see the working page :smiley: 

> It would be great if we would be able to pass things to the layout file

I completely agree! This would make the macro plugin easier to implement as well.

Right now, Eta passes `it` to the template, and I think it might be nice to have that as a default -- e.g. calling `<% layout("./layout") %>` calls the layout with `Object.assign({body:tR},it)`.

Maybe something like `Object.assign({body:tR},passedParams || it)`, so it falls back to `it` if the user doesn't explicitly pass in options?

**Comment by willemmulder** [comment]
Haha yes, after a hard reload, it works fine again! :)

And yes `Object.assign({body:tR},passedParams || it)` makes perfect sense! 👍

**Comment by nebrelbug** [comment]
@willemmulder do you have an opinion on whether it would be confusing to merge `it` and the custom arguments?

```js
Object.assign(passedParams || it, {body:tR})
```

vs

```js
Object.assign(it, {body:tR}, passedParams)
```

I'm leaning toward the second option, because it would allow a user to override `body`. In the first option, we can't allow that because with nested layouts, `body` would be set to `it.body` rather than `tR`.

**Comment by nebrelbug** [comment]
@willemmulder actually, never mind. I decided the second option was best because it leads to less confusing / more consistent behavior :+1:

**Comment by willemmulder** [comment]
@nebrelbug Yep, definitely second option, good choice 👍

**Comment by nebrelbug** [comment]
@willemmulder just published https://github.com/eta-dev/eta/releases/tag/v1.11.0, with support for passing data to layouts :tada:

**Comment by willemmulder** [comment]
Great, thanks!

**Comment by nebrelbug** [comment]
By the way (and for anyone who comes to this thread in the future) I just published a plugin called https://github.com/nebrelbug/eta_plugin_mixins that adds this functionality to Eta.

**Comment by willemmulder** [comment]
Nice work again! 👍
