### ISSUE TITLE
includeFile not working

### ISSUE THREAD

**Issue by SilentVoid13** [eta-dev/eta#100]
**Describe the bug**

`includeFile` is not working, it just throws `ReferenceError: includeFile is not defined`.

**To Reproduce**

Run `await eta.Render("<%~ includeFile("./MyFile") %>", {...});` to experience the bug.

**Package & Environment Details**

 - Environment: Node
 - Version: v15.12.0

**Additional context**

It looks like it's just not in the default config: https://github.com/eta-dev/eta/blob/7102b66f3e0c3ac7852ded66542035b3db36b6f9/src/config.ts#L111-L129 

Same thing happens when running `console.log(E);`, it is just not defined.

**Comment by shadowtime2000** [comment]
`includeFile` doesn't work with `render`. Use it with `renderFile`.
