### ISSUE TITLE
Cache fallback to file, to behave similar to EJS 'include'

### ISSUE THREAD

**Issue by ajmas** [eta-dev/eta#107]
**Is your feature request related to a problem? Please describe.**

I am coming from EJS and noticed the `include` functionality doesn't behave in the same way. In ETA it expects to only get templates from the cache, so the cache needs to be pre-populated.

**Describe the solution you'd like**

The suggestion is to fall back to the includeFile() function and then load the result into the cache. An alternative to providing the code as part of the code base, would be to provide documentation on how the developers using the package could do the same. 

**Describe alternatives you've considered**

Iterating through the views directory and filling the cache myself.

**Additional context**

**Comment by shadowtime2000** [comment]
Is there any reason you can't just use `includeFile`? Things like this can just get resolved by reading the documentation per say and learning that `include` doesn't behave the same way in Eta as EJS

**Comment by shadowtime2000** [comment]
Closing because of no response/inactivity. Feel free to comment on here with your response to my question and I can reopen this.
