### ISSUE TITLE
how use layouts with eta?

### ISSUE THREAD

**Issue by TechComet** [eta-dev/eta#11]
Hi,

how use layouts in templates with eta?

**Comment by boxymoron** [comment]
I'm having issues calling <%- E.include('some/path') %> from inside a template myself. Always get: Eta Error: Could not fetch template "some/path"

Looking at the code it looks like includes go directly to the Cache (i.e. they don't get resolved). Looks like the function function includeHelper(templateNameOrPath, data) hasn't been implemented completely.

I don't think this project is production ready.

**Comment by nebrelbug** [comment]
Hi @boxymoron! Sorry if I didn't explain it well in the documentation, but you need to use `E.includeFile` if you want to include template files.

**Comment by nebrelbug** [comment]
@TechComet hi! Right now Eta doesn't have layouts support built-in.

I'm working on creating a plugin that will add layouts support.

In the meantime, you can do something like this:

```ejs
<% /* template.eta */ %>
<% var body = (it)=>{var tR="" %>

Hi, this is the body template

<h1><%= it.title %></h1>

<% return tR } %>

<%~ E.includeFile('./layout.eta', {body: body}) %>
```

```ejs
<% /* layout.eta */ %>
This is the body
================

<%~ it.body({title: "Awesome Title"}) %>
```

```js
// index.js
var Eta = require('eta')

eta.renderFile("./template.eta", { name: "Ben" }, function (err, rendered) {
  console.log(rendered)

  // This is the body
  // ================
  //
  // Hi, this is the body template
  //
  // <h1>Awesome Title</h1>

})
```

See https://github.com/eta-dev/eta/issues/10 for an explanation.

**Comment by TechComet** [comment]
Thank you
please add to eta code not wirte plugin to install
