### ISSUE TITLE
Publich eta-vscode on open-vsx

### ISSUE THREAD

**Issue by AurangAsif** [eta-dev/eta#114]
**Is your feature request related to a problem? Please describe.**
I am using an instance of [cdr/code-server](https://github.com/cdr/code-server). Legally, they cannot use the microsoft extension marketplace. So they use alternatives such as https://open-vsx.org/. It would be really nice if the `eta-vscode` extension could be published there too.

**Describe the solution you'd like**
I would like the `eta-vscode` vscode extension to be published on https://open-vsx.org/

**Describe alternatives you've considered**
Using EJS as they have an extension on `open-vsx`

**Additional context**
I would rather use ETA because of the speed claims

**Comment by shadowtime2000** [comment]
@AurangAsif Sorry for the late repy, but can you make this issue in the `eta-vscode` repository instead? 

[shadowtime2000/eta-vscode](https://github.com/shadowtime2000/eta-vscode)
