### ISSUE TITLE
CDN version should be included in `https://github.com/eta-dev/eta/releases`

### ISSUE THREAD

**Issue by patarapolw** [eta-dev/eta#123]
**Is your feature request related to a problem? Please describe.**

I find absolutely no way to use Eta in Vite, other than

```sh
cp -r ./node_modules/eta/dist/browser ./public/vendor/eta
rm -r ./public/vendor/eta/*.dev.*
```

```ts
declare global {
  interface Window {
    Eta: typeof import('eta')
  }
}

const script = document.createElement('script')
script.src = '/vendor/eta/eta.min.js'
document.body.append(script)

const Eta = window.Eta

export default Eta
```

And `vite.config.js`

```ts
// https://vitejs.dev/config/
export default defineConfig({
  build: {
    rollupOptions: {
      external: /^\/vendor\//,
    },
  },
})
```

I also notice that `eta.min.js` does not exist anywhere in Github, only in NPM and various CDN's.

**Describe the solution you'd like**

1. Deploy `eta.min.js` and `eta.min.js.map` to `https://github.com/eta-dev/eta/releases`
2. Solve https://github.com/eta-dev/eta/issues/122

**Additional context**

https://eta.js.org/docs/learn/install should include Browser (non CDN).

**Comment by shadowtime2000** [comment]
@patarapolw Sorry for the bad question, but why is it necessary for the CDN build to be included in the Github release? I'm a bit wary of adding it there because I'd rather only keep the source code in the Github releases

**Comment by patarapolw** [comment]
To facilitate ones who doesn't use NPM at all.

Same reasons as using Github Action to build on Github, and upload to binaries to release page (tags only).

**Comment by nebrelbug** [comment]
For JavaScript packages, the standard is to host on the NPM registry. Downloads can be downloaded from there, from unpkg, or from jsDelivr. 

I think that it's not necessary to distribute the CDN files ourselves, and would just add additional complexity to the build process.
