### ISSUE TITLE
How to convert markdown files to eta?

### ISSUE THREAD

**Issue by salemalem** [eta-dev/eta#136]
I know there are tools to convert .md files to .html
How about .md -> .eta?

**Comment by NewtTheWolf** [comment]
First of all, excuse my English.

The thing is, eta is a template engine for rendering template files with custom variables like `ejs` *Embedded JavaScript*.

with eta you can also render `ejs` files, i.e. you can simply convert the `md` files to `html` and then change the extension from `html` to `eta/ejs`

i don`t know how good these converters are, but finally you have to program functions like displaying variables yourself

if i have written something wrong you are welcome to complement me

**Comment by salemalem** [comment]
https://github.com/salemalem/deno-twd-drash/blob/main/drash-resources/pages/single_tutorial_resource.js#L22
I, indeed, solved this problem using rimu.
