### ISSUE TITLE
Can you add a badge for eta?

### ISSUE THREAD

**Issue by salemalem** [eta-dev/eta#138]
I am using eta in my [blog engine](https://github.com/salemalem/deno-twd-drash) project. I already added Tailwind CSS, Drash, and Deno badges, now since I am using eta with [tengine[(https://deno.land/x/drash_middleware@v0.7.4/tengine) I need to add eta badge too)
Can you add it so I can add it to my project?

**Comment by shadowtime2000** [comment]
@salemalem [Here] is one, I will add it in a page on the docs soon.
