### ISSUE TITLE
Documentation is not beginner friendly

### ISSUE THREAD

**Issue by aoliadi** [eta-dev/eta#14]
I feel the hard stuff was addressed straight away, while very basic info was omitted. What file extension do I use? What file do I link my html or eta file to in the node_modules folder? Not everyone has used EJS before. Besides that documentation (EJS's) is far from explanatory.

I'd prefer a documentation where the user is held by hand. Empathy for a beginner - like me. Thanks in advance.

**Additional context**
After knowing how to do this, I can assist in documentation writings and more explanations. If I can be allowed. Thanks in advance. I eagerly await a response. I need to get this template done. :)

**Comment by nebrelbug** [comment]
@aoliadi I apologize for the lousy documentation. In the meantime, here's a quick example of using Eta with Node.js (if you're using Deno let me know).

```ejs
<% /* views/template.eta */ %>
This is an Eta template. My favorite food is <%= it.food %>
```

```js
// index.js

var eta = require("eta")
var path = require("path")

// Set Eta's configuration
eta.configure({
  // This tells Eta to look for relative templates (like "./template", "./template.eta", "template.eta")
  // In the /views directory
  views: path.join(__dirname, "views"), 
  // This tells Eta to look for absolute templates (like "/template", "/template.eta")
  // In the /views directory
  root: path.join(__dirname, "views")
})

// You could also write renderFile("template"), renderFile("./template"), renderFile("/template"), etc.
// Eta assumes the .eta extension and will search for files ending in it if you don't specify an extension
eta.renderFile("template.eta", { food: "cake" }).then((rendered) => {
  console.log(rendered) // "This is an Eta template. My favorite food is cake"
})
```

> After knowing how to do this, I can assist in documentation writings and more explanations. If I can be allowed.

That would be wonderful!

**Comment by nebrelbug** [comment]
Now, for partials :grinning: 

Let's say we create a new file, `footer.eta`:

```ejs
<% /* views/footer.eta */ %>
<footer>This is a footer!</footer>
```

We want to include it the bottom of our `template.eta` file. So we update it to:

```ejs
<% /* views/template.eta */ %>
This is an Eta template. My favorite food is <%= it.food %>

<% /* equivalent to E.includeFile("footer") or E.includeFile("/footer.eta"), etc. */ %>
<% /* note that we use '~' instead of '='. This is so Eta doesn't HTML-escape the partial */ %>
<%~ E.includeFile("./footer") %>
```

Now, running `node index.js` returns:

```html
This is an Eta template. My favorite food is cake
<footer>This is a footer!</footer>
```

:tada: :tada: :tada:

**Comment by nebrelbug** [comment]
@aoliadi I hope this helps! Let me know if you have any questions.

**Comment by nebrelbug** [comment]
@aoliadi on second thought, don't actually use the `root` option in the configuration :+1:

**Comment by nebrelbug** [comment]
Since I've updated the documentation at https://eta.js.org, I'll close this now :smiley:
