### ISSUE TITLE
Doesn't read layout partials from partials cache.

### ISSUE THREAD

**Issue by coolaj86** [eta-dev/eta#141]
# Describe the bug

I'd expect that I could define a layout partial as documented:

```js
Eta.templates.define("layouts/default", Eta.compile("<section><% it.body %></section>"));

console.log(Eta.templates.get("layouts/default")) // Function
```

And then to be able to use it, like so:

```js
Eta.render(`
<% layout("layouts/default") %>
Hello, <% it.name %>!
`, { name: "Tom" })
```

But instead I get an error:

```txt
Error [Eta Error]: Could not find the template "layouts/default". Paths tried: /home/app/layouts/default.eta
```

# To Reproduce

Here's my example project:

```js
'use strict';

let Fs = require('fs').promises;
let Path = require('path');
let Eta = require('eta');

let tplDir = '.';

Eta.configure({ tags: ['{{', '}}'], views: ['.'] });

async function render(name, vars) {
  let prefixedName = 'layouts/transactional-email';

  // ex: ./layouts/transactional-email.eta.mjml.html
  let path = Path.resolve(tplDir, prefixedName + '.eta.mjml.html');
  let tmplText = await Fs.readFile(path, 'utf8');
  Eta.templates.define(prefixedName, Eta.compile(tmplText));

  console.log('Has layout?', Eta.templates.get('layouts/transactional-email'));
  // confirmed: layout partial exists in the cache

  // ex: ./welcome.eta.mjml.html
  path = Path.resolve(tplDir, name + '.eta.mjml.html');
  tmplText = await Fs.readFile(path, 'utf8');

  return Eta.render(tmplText, vars);
}

render('welcome', { name: 'Tom' });
```

`welcome.eta.mjml.html`:

```html
{{ layout("layouts/transactional-email") }}
<mj-section>
  <mj-column>
    <mj-text>Hello, {{= it.name }}!</mj-text>
  </mj-column>
</mj-section>
```

`layouts/transactional-email.eta.mjml.html`:

```html
<mjml>
  <mj-head>
    <!-- stuff -->
  </mj-head>
  <mj-body>{{~ it.body }}</mj-body>
</mjml>
```

**Expected behavior**

Should load from defined partials before failing with a not found on filesystem error.

**Package & Environment Details**

- node v16.x
- eta@latest

**Comment by coolaj86** [comment]
# Workaround

1. Set `views: ["."]`
   ```js
   Eta.configure({ tags: ['{{', '}}'], views: ['.'] });
   ```
2. Use full file name (thank goodness ETA honors file extensions!!)
   ```html
   {{ layout("layouts/transactional-email.eta.mjml.html") }}
   <mj-section>
     <mj-column>
       <mj-text>Hello, {{= it.user.given_name }}!</mj-text>
     </mj-column>
   </mj-section>
   ```

**Comment by shadowtime2000** [comment]
@coolaj86 This is actually not a bug. The docs specify that if `includeFile` is not specified then it will fall back to `include` so that is where the solution lies. 

```js
Eta.configure({
    includeFile: undefined
});
 
Eta.templates.define("layouts/default", Eta.compile("<section><%~ it.body %></section>"));

Eta.render(`
<% layout("layouts/default") %>
Hello, <%= it.name %>!
`, { name: "Tom" });
```
By making `includeFile` undefined Eta will then search through defined templates for the layouts instead.

**Comment by coolaj86** [comment]
The docs are confusing on that - it sounds like it’s saying you can override includeFile or include and gives a function signature, but never shows an example of how one would create such a function - return values, etc.

Wouldn’t it make more sense that it always try `include` and then always fall back to `includeFile` if it’s not already in the cache?

Isn’t that how the other partials work?

Anyway, thank you.
