### ISSUE TITLE
ternary conditional operator

### ISSUE THREAD

**Issue by AmirABody** [eta-dev/eta#143]
Hello there,
hope you're fine,

Isn't it possible to use ternary conditional operators in eta template views?

As an example:
```<text x="0" y="0" fill="<% = it.condition ? it.value1 : it.value2 %>"/>```

It would be great if we could use this feature in our template views, it makes our code clean and concise.
Thanks!

**Comment by shadowtime2000** [comment]
@AmirABody You can use ternary operators because Eta interpolates JS. 

```
<text x="0" y="0" fill="<%= it.condition ? it.value1 : it.value2 %>"/>
```

100% works. I'll add this to the docs soon though.
