### ISSUE TITLE
global config not working

### ISSUE THREAD

**Issue by drypot** [eta-dev/eta#148]
I've been trying Eta since yesterday.

I hoped to turn on cache by,
`eta.config.cache = true` or `eta.configure(...)`

but the cache didn't seem to work.

So I turned on debugger.

I found that global `config` object in `getConfig` function was not mine.
it still have `cache=false`
strange.
I'm not sure what the problem is.

but, I found workaround with Express settings like this.

`express.set('view options', {
  cache: true,
  autoTrim: false
})
`

this works.

---

I'm trying Eta with 

TypeScript 4.4.3.
Node 16.3.0.
Express 4.17.1

package.json 
"type": "module",

**Comment by drypot** [comment]
I think there was something I didn't know well.

I've read the official Express documentation that explains the `view cache` option.

In express, indirectly setting Eta cache with the express `view cache` option looks right.

Yesterday it looked weird, but now it looks natural. :)

**Comment by shadowtime2000** [comment]
@drypot Is there any exact code I should use to reproduce the problem if you are still facing it?

**Comment by drypot** [comment]
At first, I didn't know how express works, so I asked a question.
But, my problem solved now.

I think the proper whay to set eta cache option in express is this.

```
express.set('view options', { cache: true })
```

it works well.
