### ISSUE TITLE
After the first occurrence of an <a> tag, dozens of <a> tags appear generated on the site

### ISSUE THREAD

**Issue by nickelswitte** [eta-dev/eta#150]
**Describe the bug**
I am developing a small website, also using eta js. On one certain sub page, I am using an `<a>` tag to link to another page. Inspecting the code in my browser, I can see that from the place there I put the `<a>` tags in the code, there are dozens of other `<a>` tags generated inside my code. 

**To Reproduce**
Not sure how to reproduce, as this only happens in certain file, and not with others with `<a>` tags.

**Expected behavior**
I'd like to have just the programmed occurences of my code, and not multiplied by 10 times or so.

**Package & Environment Details**
 - Environment: Node v16.3.0, 
 - Multiple browsers (Edge, Firefox)

**Additional context**

My generating code
```
<% layout('./basic', it) %>

<div class="columns">
    <div class="column">

        <% 
        let i = 0;
        %>

        <% // console.log(it.albums[0]) %>

        <% while (i < it.albums.length) { %>
            
            
            <%~ includeFile('./templates/albumPreview', { 
                albumTitle: it.albums[i].data.title,
                albumSubtitle: it.albums[i].data.subtitle,
                href: '/' + it.albumRouting + '/' + it.albums[i].name,
                thumbnail: it.albumsPathPrefix + it.albums[i].name + '/' + it.albums[i].data.thumbnail
            }); %>

            <% i += 2; %>

        <% } %>

    </div>
```

And the included file
```
<div class="block">
    <div class="card">
        <a href='<%= it.href %>'>
            <div class="card-image">
            
                
                <figure class="image">
                    <img src="<%= it.thumbnail %>" alt="Placeholder image">
                </figure>

                <div class="text-block">
                    <h1 class="is-size-4"><%= it.albumTitle %></h1>
                </div>
            </div>
        <a>
    </div>
</div>
```

**Screenshots**
Find here a screenshot of the code which I inspect in my browser
![grafik](https://user-images.githubusercontent.com/36443026/140097053-d4258bd9-7a39-488b-9b00-4d68e926c055.png)

**Comment by nickelswitte** [comment]
Some additional context:

This issue even reaches into eta templates, which are referenced from the basic template `<% layout('./basic', it) %>` (in line 1 from code example above) and messes up my footer.

Find here the `footer.eta`
```
<footer class="footer">
    <div class="content ">
        <div class="columns">
            <div class="column is-6 is-offset-3">
                This page was created by <a href="#" class="subtleLink">Me</a> 
                
            </div>
        </div>
    </div>
</footer>
```

And here the generated code in the browser:
```
</a><footer class="footer"><a>
    </a><div class="content "><a>
        </a><div class="columns"><a>
            </a><div class="column is-6 is-offset-3"><a>
                This page was created by </a><a href="#" class="subtleLink">Me</a> 
            </div>
        </div>
    </div>
</footer>

```

As you can see, the words `This page was created by`, is now clickable, which is not expected.
![grafik](https://user-images.githubusercontent.com/36443026/140103286-fc8117cc-cbcf-4ab7-b05d-34303103e047.png)


Somehow it seems, every tag is encapsulated in `<a>` tags..

**Comment by avihavai** [comment]
Hi! (disclaimer: I'm not in any way involved in this project). It seems that the `<a>`-tag is not properly closed in the template file that you're including. Try closing the `a` tag on the third last line of the included file, i.e. using `</a>` instead of `<a>`.
