### ISSUE TITLE
layout function with template name support

### ISSUE THREAD

**Issue by linux-china** [eta-dev/eta#151]
Now layout load eta layout file from file system  alike following code: 

```ejs
<% layout(filepath) %>
```

Any plan to load layout from  templateName alike 'include' function. 

```javascript
include(
  templateName,
  Object.assign(it, { body: templateResult }, layoutParameters)
)
```

Why?  Now I use esbuild to import eta template,  and layout with templateName support is friendly for bundle. 

```
// import all partials
import button1 from "./partials/button.eta";
// import template view
import indexTemplate from "./views/index.eta";
```

**Comment by shadowtime2000** [comment]
@linux-china Have you tried setting the config so that `includeFile: undefined`, because if `includeFile` function is `undefined` then it will automatically fall back to `include` which will fetch a template based off of template name.

**Comment by linux-china** [comment]
@shadowtime2000  yes, it works. Thanks 👍

**Comment by linux-china** [comment]
I created esbuild plugin for Eta:  https://www.npmjs.com/package/esbuild-plugin-eta
