### ISSUE TITLE
Deno deploy error: Code generation from strings disallowed for this context

### ISSUE THREAD

**Issue by ynwd** [eta-dev/eta#168]
This code is working fine with deno-cli (1.20.4)

```ts
import { serve } from "https://deno.land/std@0.133.0/http/server.ts";
import { render } from "https://deno.land/x/eta@v1.12.3/mod.ts";

function handler(): Response {
  const html = <string> render(
    "<h4>The answer to everything is <%= it.answer %></h4>",
    { answer: 42 },
  );

  const headers = new Headers();
  headers.set("Content-Type", "text/html; charset=UTF-8");

  return new Response(html, { headers });
}

console.log("Listening on http://localhost:8000");
await serve(handler);
```

but if I run it at deno-deploy [playground](https://dash.deno.com/playground/strong-mouse-85), I got this error:
```

EvalError: Code generation from strings disallowed for this context
    at new Function (<anonymous>)
    at compile (https://deno.land/x/eta@v1.11.0/compile.ts:29:16)
    at handleCache (https://deno.land/x/eta@v1.11.0/render.ts:13:24)
    at render (https://deno.land/x/eta@v1.11.0/render.ts:69:16)
    at Server.handler (file:///src/main.ts:4:18)
    at Server.#respond (https://deno.land/std@0.133.0/http/server.ts:220:43)
    at Server.#serveHttp (https://deno.land/std@0.133.0/http/server.ts:254:26)

```

**Comment by alevroub** [comment]
The main issue is that Deno deploy does not allow javascript code evaluated at runtime. The following will return the same error:

```
import { serve } from "https://deno.land/std@0.133.0/http/server.ts";
import { render } from "https://deno.land/x/eta@v1.12.3/mod.ts";

function handler(): Response {
  return new Response(`${eval('2 + 2')} = 4`);
}

await serve(handler);
```

This is most likely related to ETA's compile function which returns a stringified function for the renderer.

https://github.com/eta-dev/eta/blob/912c2e3648f5bb28a166d0cc1050381f37942d8e/deno_dist/compile-string.ts#L27

**Comment by shadowtime2000** [comment]
That's correct, this problem emerges from the fact Eta is built on compiling functions and then rendering it which allows for faster speed. 

I haven't toyed around with Deploy all too much, but I think the solution here would be to compile your templates beforehand and stringify them and put them into seperate importable functions, so it isn't compiled on demand. Let me know if that doesn't work.

**Comment by shadowtime2000** [comment]
Closing, as this should be resolved then.
