### ISSUE TITLE
Usage: App.locals

### ISSUE THREAD

**Issue by rubiin** [eta-dev/eta#169]
How does eta handle app.locals provided in expressjs
following this: https://eta.js.org/docs/examples/express

when is set `app.locals.someFunction = function(arg){
return "hello"+arg;
}`

and access it as `<%= it.someFunction('mike') %>`
i get , someFunction is not defined

**Comment by shadowtime2000** [comment]
@rubiin Hi, sorry for responding so late, but I am not able to reproduce this problem. My reproduction is [here](https://github.com/shadowtime2000/eta-issue-169), though I do not commonly use Express, so it may not be the best.
