### ISSUE TITLE
Deno Deploy: Deno.lstatSync is not a function

### ISSUE THREAD

**Issue by sejori** [eta-dev/eta#172]
**Describe the bug**
Eta is currently unusable on Deno Deploy because it uses `Deno.existsSync` which uses `Deno.lstatSync`underneath which is not currently supported by Deploy.

**To Reproduce**
Deploy any script that imports and uses the `renderFile` eta method to Deno Deploy

**Logs**
```
TypeError: Deno.lstatSync is not a function at existsSync (https://deno.land/std@0.97.0/fs/exists.ts:19:14) 
  at searchViews (https://deno.land/x/eta@v1.12.3/file-utils.ts:80:17) 
  at getPath (https://deno.land/x/eta@v1.12.3/file-utils.ts:115:27) 
  at renderFile (https://deno.land/x/eta@v1.12.3/file-handlers.ts:155:29)
```

**Package & Environment Details**
 - Environment: Deno Deploy (deployctl)
 - Version: 1.1.0

**Comment by sebringrose** [comment]
I think the fix is to swap out the synchronous `fs` imports in `file-utils.ts` and `file-methods.ts` for their asynchronous counterparts (and probs worth updating to a more recent fs version while in there). This may require quite a large refactor to support Promises however.

**Comment by christian-dale** [comment]
Here is a temporary fix that allows you to use templates on Deno Deploy :)

```
Eta.config.includeFile = function(path, data) {
  return Eta.templates.get(path)(data, Eta.config);
};
```

I would then write something like this:

```
Eta.templates.define("main", Eta.compile(
  await Deno.readTextFile(`${Deno.cwd()}/views/main.eta`)));

const template = await Eta.render(await Deno.readTextFile(`${Deno.cwd()}/views/home.eta`), {
    title: "My webpage"
  });
```

And this in a template:

```
// home.eta

<% layout("main") %>

<h1>Welcome to my home page</h1>
```

```
// main.eta

<!DOCTYPE html>
<html lang="en">
<head>
    <title><%= it.title %></title>
</head>
<body>
    <%~ it.body %>
</body>
</html>
```

**Comment by nebrelbug** [comment]
@sebringrose thanks for reporting on this issue. 

> I think the fix is to swap out the synchronous fs imports in file-utils.ts and file-methods.ts for their asynchronous counterparts (and probs worth updating to a more recent fs version while in there). This may require quite a large refactor to support Promises however.

This is correct. Luckily, we're working on the next version of Eta, which will include refactored and fully asynchronous file handling :)

@christian-dale thanks for contributing a temporary fix!

**Comment by matthewmorek** [comment]
I am encountering the same error, and also using the above `Deno.readTextFile()` doesn’t work in the context of Supabase Edge Functions, so I’m stuck currently.

Eta seem to be the best option for server-side templates, which I try to use for compiling and sending emails. Happy to help with diagnosing, testing, triaging, etc.

**Comment by nebrelbug** [comment]
@matthewmorek I haven't been able to think of a way to fix this in version 2, so it will probably have to wait until version 3. 

But, I think you should be able to use @christian-dale's solution by modifying it slightly to use `readFile`.

```js
const decoder = new TextDecoder("utf-8");
const template = await Deno.readFile(`${Deno.cwd()}/views/main.eta`);
Eta.templates.define("main", decoder.decode(template));
```

**Comment by matthewmorek** [comment]
@nebrelbug It works well locally, however the particular deployment env in using (Supabase) doesn't allow read/write to FS, so the workaround is to us a ESM template literal import, then process it as you would any other string.

**Comment by nebrelbug** [comment]
Great workaround!

**Comment by sebazelonka** [comment]
> @matthewmorek I haven't been able to think of a way to fix this in version 2, so it will probably have to wait until version 3.
> 
> But, I think you should be able to use @christian-dale's solution by modifying it slightly to use `readFile`.
> 
> ```js
> const decoder = new TextDecoder("utf-8");
> const template = await Deno.readFile(`${Deno.cwd()}/views/main.eta`);
> Eta.templates.define("main", decoder.decode(template));
> ```

Hello, I'm facing the same issue and I'm a bit lost.

I have this code:

```ts
const html = await renderFile(`/base.eta`, {
    title: attrs.title,
    content: markup,
    links: { postLink: outputFilename },
  });
```

what is expected to do here?

This is my `deps.ts`

```ts
export { extract } from "https://deno.land/std@0.181.0/front_matter/any.ts";
export { renderMarkdown } from "https://deno.land/x/markdown_renderer@0.1.3/mod.ts";
export {
  renderFile,
  configure,
  templates,
} from "https://deno.land/x/eta@v2.0.1/mod.ts";

```
I added this 2 lines 

```ts
const template = await Deno.readFile(`${templatesDir}/base.eta`);

templates.define("base", decoder.decode(template));
```

but I get this error:

```
Argument of type 'string' is not assignable to parameter of type 'TemplateFunction'.deno-ts(2345)
```

I know this is a newbie question, but this is what I am :)

**Comment by nebrelbug** [comment]
@sebazelonka sorry, there was a typo in my previous comment. You'd have to write `Eta.templates.define("main", Eta.compile(decoder.decode(template)));`

I can't check this right now, but will you let me know if this works?

```js
const template = await Deno.readFile(`${templatesDir}/base.eta`);

Eta.templates.define("base.eta", Eta.compile(decoder.decode(template)));

Eta.configure({cache: true});

let res = await Eta.renderFile(`base.eta`, {
    title: attrs.title,
    content: markup,
    links: { postLink: outputFilename },
  });
```

**Comment by nebrelbug** [comment]
For all those using Deno Deploy, they just added support for Node.js built-ins like `fs`. I believe file handling should now work! Can anyone confirm that for me?

**Comment by nebrelbug** [comment]
I've just tested and can confirm that eta.renderFile is functional with the latest versions of Deno Deploy. :tada: :tada:
