### ISSUE TITLE
Package cannot be imported in TS project compiled with NodeNext

### ISSUE THREAD

**Issue by Josh-Cena** [eta-dev/eta#173]
While working on https://github.com/facebook/docusaurus/pull/7586, `eta` was one of the packages blocking a successful compilation.

**To Reproduce**

`yarn add typescript eta`

tsconfig.json:

```json
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true
  }
}
```

Add a TS file with:

```ts
import eta from "eta";
```

It errors: "Could not find a declaration file for module 'eta'. 'node_modules/eta/dist/eta.cjs' implicitly has an 'any' type."

The reason is because eta's package.json `exports` does not have a `types` field for each entry, so TS can't associate the js files with their types. (Before, TS would _always_ use the root `types` entry).

Fixing this is a bit involved, because the package also has `"type": "module"`, which causes the .d.ts files to be interpreted as ESM. Therefore, even for .d.ts files, explicit extensions are required. I'm not sure what the best way to fix this is, so I just want it to be in your backlog first.

**Expected behavior**

Successful TS compilation

**Package & Environment Details**
 - Environment: Node 18.3.0
 - Version: 1.12.3

**Additional context**

There's some basic writeup here: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#package-json-exports-imports-and-self-referencing I can't find a more comprehensive guide.

**Comment by nebrelbug** [comment]
@jakubmazanec just added a "types" field to the `exports` entry in package.json, but I'll leave this open because the `exports` field needs some more substantial changes.

**Comment by nebrelbug** [comment]
@Josh-Cena this should be working now!
