### ISSUE TITLE
async does not work inside nested templates

### ISSUE THREAD

**Issue by jukefr** [eta-dev/eta#175]
**Describe the bug**
Async functionnality does not work inside included templates

**To Reproduce**
What works : 
```typescript
    return renderAsync(
      '<%~ include("README.template.md", {...it}) %> <%= await fetch("someApi").then(r => r.json()).then(r => JSON.stringify(r)) %>',
      {
       ...
      },
      {
        async: true,
      },
    ) as Promise<string>;
```
Will render the template

Now if i put this call inside of the readme template
```typescript
    return renderAsync(
      '<%~ include("README.template.md", {...it}) %>',
      {
       ...
      },
      {
        async: true,
      },
    ) as Promise<string>;
```
With this template as readme.template.md
```markdown
<%= await fetch("someapi").then(r => r.json()).then(r => JSON.stringify(r)) %>
```
I get the following error
```
2022-07-02T20:09:39.433Z ERROR Eta Error: Bad template syntax

missing ) after argument list
=============================
var tR='',__l,__lP,include=E.include.bind(E),includeFile=E.includeFile.bind(E)
function layout(p,d){__l=p;__lP=d}
tR+=E.e(await fetch("someapi").then(r => r.json()).then(r => JSON.stringify(r)))
if(__l)tR=includeFile(__l,Object.assign(it,{body:tR},__lP))
if(cb){cb(null,tR)} return tR

    at EtaErr (https://deno.land/x/eta@v1.12.3/err.ts:26:15)
    at compile (https://deno.land/x/eta@v1.12.3/compile.ts:56:13)
    at render (file:///home/user/Documents/@kay/readme-manager/render.ts:25:9)
    at async mod (file:///home/user/Documents/@kay/readme-manager/mod.ts:121:24)
    at async file:///home/user/Documents/@kay/readme-manager/mod.ts:165:1
```

Oddly enough pasting this mangled output into an editor and formatting it reveals that is syntactically correct and not missing any `)`

See above.
It is also the same outcome if I define the function on it and use it with it.myFn() later in the template.

**Expected behavior**
Expected async functions to work inside of templates.

**Package & Environment Details**
see https://deno.land/x/readme_manager@v2.1.3 namely render and bootstrap

**Comment by jukefr** [comment]
it looks like it has something to do with using single quotes `'` and not double quotes `"` inside the fetch call actually also

**Comment by jukefr** [comment]
ok but however the issue seems to remain, i am not able to use await inside of included templates, is there any way to do so or should all async calls be done at parent and variables passed to children ?

**Comment by shadowtime2000** [comment]
Since `Eta.config.async` has a default value of `false`, then this problem likely occurs from the defining of templates with `Eta.templates.define`, as using `Eta.compile` with that will have `async` set to false meaning the produced function isn't async. So try setting `async: true`, like this:
```javascript
Eta.templates.define("README.template.md", Eta.compile(`<%= await fetch("someapi").then(r => r.json()).then(r => JSON.stringify(r)) %>`, { async: true }));
```

You could also just set the global `async: true` like this:
```javascript
Eta.config.async = true;
```

@jukefr Let me know if this solves your problem or not.

**Comment by jukefr** [comment]
Yes that works, I just have to `await` the `include` calls also, thank you very much !
