### ISSUE TITLE
“strng.replace” is not a function

### ISSUE THREAD

**Issue by ScolderCreations** [eta-dev/eta#177]
**Describe the bug**
ETA attempts to use “strng.replace”, which does not exist of course.

**To Reproduce**
1. Use eta.Render function as intended.

**Expected behavior**
ETA should use string.replace, not strng.replace. This would avoid the error(?)
**Screenshots**

**Package & Environment Details**
 - Environment: NodeJS
 - Version: 16.13.2

**Comment by shadowtime2000** [comment]
This problem doesn't come out of `string.replace` being used instead, `strng` is an internal variable used inside of the parsing function, and is used for whitespace trimming. Could you share what exactly your template is, because it doesn't seem this problem is showing up at all for me.

**Comment by JonnyPower** [comment]
@shadowtime2000 I see the same when trying to evaluate something like; `<%= it.name.toUpperCase().replaceAll("foo", "bar"); %>` - seems the first string method returns strng and therefore can't be chained?

**Comment by nebrelbug** [comment]
Closing this as stale.

**Comment by ScolderCreations** [comment]
Still having the problem.

**Comment by nebrelbug** [comment]
@ScolderCreations could you send me a reproducible example of the error?

**Comment by lopopolo** [comment]
I was able to reproduce this by mistakenly passing a `Buffer` to `Eta.renderString` instead of a `String`. I got the buffer from calling `fs.readFile` without an encoding argument.
