### ISSUE TITLE
Safe access variables (whether present or not)

### ISSUE THREAD

**Issue by bacloud22** [eta-dev/eta#183]
I have been using EJS a lot, and one of the pains is this exact situation:

```html
<% if(typeof section != 'undefined'){ %>
     <soMuchHTML></soMuchHTML>
<% } %>
```

It would be great to have a special new tag like `<%safe %> <% } %>` where variables are evaluated whether they are defined or not, if only one access fail occurs (undefined), the whole block is discarded.

**Comment by shadowtime2000** [comment]
@bacloud22 What you're proposing would require a JS parser to detect variables referenced and then add in wrapper code to detect if they exist or not, which seems like it would unnecessarily increase the size of Eta by a lot and would just be out of the scope of the project. Maybe you would want this feature as a [plugin](https://eta.js.org/docs/learn/plugins) instead?

**Comment by bacloud22** [comment]
That is true, I ignored the fact that this is a matter of a runtime evaluation. so it is to the developer to deal with.
I rather didn't pay attention 
agreed
