### ISSUE TITLE
Safe access variables again,

### ISSUE THREAD

**Issue by bacloud22** [eta-dev/eta#184]
Similarly to this issue
https://github.com/eta-dev/eta/issues/183

It would be great to have a safe tag as the following: 
Instead of each time checking a variable like:

`<% if(typeof section != 'undefined' && section == 'blogs'){ %>`

It would be great to have:

`<safe% if(section == 'blogs'){ %safe>` without failing at all if `section` doesn't exist.

**Comment by shadowtime2000** [comment]
Sorry, but it doesn't seem that there is much separating this proposal from #183. What's the difference?

**Comment by bacloud22** [comment]
true that it would require the same approach of parsing JS.
Although it is not the same exact case.
Maybe a workaround would be to let the developer declare 'clearly' in a block, used variables, so that at least they are declared.
In most cases, this would be useful because declaring a variable won't change any logic working with the variable and at the same time, would lesser `ReferenceError` errors.

now, I can think of for instance having a partial to include everywhere with all possible variables like:

```js
var section = "<%= section %>"
// ... and a long list of variables
```

but this is not the best in my opinion, I would like to see something straightforward like:

```js
<%safe %> var1, var2, var3, ...<% } %>
```
These variables would be then evaluated as usual by ETA (`it`)

**Comment by shadowtime2000** [comment]
@bacloud22 Sorry, I'm getting a little confused here. What exactly is meant to be the output of this `<% declare %>` block then, if the variables are being evaluated as usual. What is the output template meant to be?

**Comment by bacloud22** [comment]
It doesn't necessarily have an output. It would declare new variables in the JavaScript scope.
