### ISSUE TITLE
Errors while trying to use Eta library

### ISSUE THREAD

**Issue by Javiani** [eta-dev/eta#186]
**Describe the bug**
I was trying to migrate from [Squirrelly](https://squirrelly.js.org/) to Eta, but I can't use this library at all. After following the instalation steps and importing the library I got some errors.

**To Reproduce**
1. yarn add eta
2. import * as Eta from 'eta'

**Expected behavior**
Be able to use the library methods and properties

**Screenshots**
<img width="1015" alt="Screen Shot 2022-07-29 at 16 40 28" src="https://user-images.githubusercontent.com/567506/181835772-6780ec13-448a-42ee-84e6-20028085e8b5.png">

**Package & Environment Details**
 - Environment: ex. Node
 - Version: ex. v14.18.0

**Comment by gitBaiano** [comment]
Hello sir! It feels like a webpack error, I had these errors when compiling to browser environment on the past and I solved it just adding this on my webpack config:

```js
module.exports = {
  //...
  resolve: {
    alias: {
      'browser': false,
//   'fs': false // consider adding this if not working also
    },
  },
};
```

**Comment by Javiani** [comment]
#

> Hello sir! It feels like a webpack error, I had these errors when compiling to browser environment on the past and I solved it just adding this on my webpack config:
> 
> ```js
> module.exports = {
>   //...
>   resolve: {
>     alias: {
>       'fs': false,
> //   'browser': false // consider adding this if not working also
>     },
>   },
> };
> ```
> 
> (but consider taking a look at https://stackoverflow.com/questions/43037590/field-browser-doesnt-contain-a-valid-alias-configuration for a normal solution)

Nice thanks @gitBaiano !!! It works like a charm.
 I had to add `path`, `fs` in the `alias` field as you suggested. 

Thanks!
