### ISSUE TITLE
typescript compile error TS1479

### ISSUE THREAD

**Issue by retorquere** [eta-dev/eta#207]
**Describe the bug**
When I try to import eta in my project with

```
import * as Eta from 'eta'
```

I get

```
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("eta")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to 'package.json'.
```

**To Reproduce**

tsconfig.json:
```
{
  "compilerOptions": {
    "allowUnreachableCode": false,
    "noUnusedLocals": true,
    "isolatedModules": true,
    "esModuleInterop": true,
    "noUnusedParameters": false,
    "importHelpers": true,
    "target": "es2017",
    "disableSizeLimit": true,
    "module": "commonjs",
    "noImplicitAny": false,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": false,
    "downlevelIteration": true,
    "resolveJsonModule": true,
    "moduleResolution": "node16",
    "skipLibCheck": true,
    "lib": [ "es2017", "dom", "dom.iterable", "webworker" ]
  },
  "include": [ "index.ts" ],
  "exclude": [ "node_modules" ]
}
```

index.ts:
```
import * as Eta from 'eta'
console.log(Eta)
```

package.json:
```
{
  "name": "tt",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "tsc --noemit"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "eta": "^1.13.0",
    "tslib": "^2.4.1",
    "typescript": "^4.9.4"
  }
}
```

type: `npx tsc --noemit`

**Expected behavior**

No error :)

**Package & Environment Details**
 - Environment: Node
 - Version: 18.9.0

**Comment by nebrelbug** [comment]
@retorquere interesting. Does this issue happen with `eta@1.12.3`?

**Comment by retorquere** [comment]
Yes.

**Comment by nebrelbug** [comment]
@retorquere ok, I think the issue is that `eta` doesn't have a separate `types` file for `eta.es.js` and `eta.cjs`. I'm going to be updating Eta's build process, so I will try to fix this sometime (hopefully) in the next few days.

**Comment by nebrelbug** [comment]
@retorquere just published a new release which aims to improve NodeNext support. Will you check to see if it resolved the issue?

**Comment by DanSnow** [comment]
We still got an error when upgrading to 1.14.1 https://github.com/storipress/unplugin-eta/pull/126

**Comment by retorquere** [comment]
For me the error is now gone, thanks!

**Comment by gurgunday** [comment]
> We still got an error when upgrading to 1.14.1 [storipress/unplugin-eta#126](https://github.com/storipress/unplugin-eta/pull/126)

Yeah, I can reproduce. PR is up.

**Comment by DanSnow** [comment]
@nebrelbug  It's fixed. Thanks 🎉
