### ISSUE TITLE
Pass variables between partials

### ISSUE THREAD

**Issue by bacloud23** [eta-dev/eta#208]
Hi,
I have a partial that includes another one, where I would like to pass a variable from the parent partial to the child.

**HTML body**
`<%~ includeFile('../big_listings_parser', it); %>`

**big_listings_parser.eta**
```
<% for (var i = 0; listings.length> 0 && i < listings.length ; i++) { %>
      <%~ includeFile('card_body', {  listing: listings[i]  } ); %>
<% } %>
```

**card_body.eta**
`// use **listing** variable`

As you can see, here I want to pass the variable `listing` which is a single value inside the loop.

### What I tried
passing multiple variables like:  `it`, `it.listings[i]`, `listings[i]` all gives errors like:

> ReferenceError: listings is not defined\n

Kindly :)

**Comment by gurgunday** [comment]
It should work in the example above? Don’t forget to call your variables using the `it` object.

So `it.listings` in the parent and `it.listing` in the child partial.

**Comment by bacloud23** [comment]
Hi @gurgunday it really doesn't

**Comment by bacloud23** [comment]
oh my bad, it does work. the problem was not in the parent partial, so it is in the child that the variable is undefined, but that an error in my child partial. Thanks a lot !!!
