### ISSUE TITLE
404 on https://rawgit.com/eta-dev/eta/master/dist/browser/eta.min.js

### ISSUE THREAD

**Issue by b1ek** [eta-dev/eta#218]
title

**Comment by nebrelbug** [comment]
@b1ek I should go through and update the documentation. Try this URL:

https://rawgit.com/eta-dev/eta/master/dist/browser.min.umd.js

**Comment by nebrelbug** [comment]
The `dist/` folder is not published on GitHub. Try using https://unpkg.com/eta

**Comment by b1ek** [comment]
> The `dist/` folder is not published on GitHub. Try using https://unpkg.com/eta

It breaks [the benchmark page](https://github.com/eta-dev/eta/blob/master/README.md?plain=1#L40). Perhaps it should load from a different URL?

**Comment by nebrelbug** [comment]
Aha, thanks for pointing that out! I just fixed the benchmark page (which was incorrectly using `Eta` instead of `eta`), the README, and eta.js.org. Everything should work now!

**Comment by panzi** [comment]
The benchmark page is broken again. Browser console says:
```
benchmark.html:105 
       GET https://raw.githack.com/eta-dev/eta/master/dist/browser.min.umd.js net::ERR_ABORTED 404 (Not Found)
benchmark.js:19 Uncaught TypeError: eta.configure is not a function
    at benchmark.js:19:5
(anonymous) @ benchmark.js:19
benchmark.html:114 Uncaught TypeError: app is not a function
    at benchmark.html:114:9
```

**Comment by b1ek** [comment]
> The benchmark page is broken again. Browser console says:
> 
> ```
> benchmark.html:105 
>        GET https://raw.githack.com/eta-dev/eta/master/dist/browser.min.umd.js net::ERR_ABORTED 404 (Not Found)
> benchmark.js:19 Uncaught TypeError: eta.configure is not a function
>     at benchmark.js:19:5
> (anonymous) @ benchmark.js:19
> benchmark.html:114 Uncaught TypeError: app is not a function
>     at benchmark.html:114:9
> ```

@nebrelbug could you take a look at this again?
