### ISSUE TITLE
it.body does not contain the body of my template when using a layout.

### ISSUE THREAD

**Issue by spr1t3-0** [eta-dev/eta#226]
**Describe the bug**
Neither it.title nor it.body seem to contain anything when i try to render a template in a layout. 
The layout is displayed, but the body is empty. 
Before using the layout, i tried to include a file partial and a partial that i defined in the singleton i created for eta, but in both cases it would just not include the contents of those partials at all. 

**To Reproduce**

Layout (views/incl/layout.eta): 
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{{ it.title }}</title>
  </head>
  <body>
    {{ it.body }}
    <footer>Copyright SomeCo, Inc.</footer>
  </body>
</html>
```

Template (views/index.eta):
```
{{ layout('./incl/layout') }}

<div id="content">
  Hello world
</div>
```

etaSingleton (services/etaSingleton.ts)

```
import * as eta from 'eta';
import { includeFile } from 'eta/dist/types/file-handlers';
import { readFileSync } from 'fs';


class EtaSingleton {
	private static instance:any;

	// eslint-disable-next-line @typescript-eslint/no-empty-function
	private constructor() {}

	static getInstance(): any {
		if (!EtaSingleton.instance) {
			eta.configure({
				tags: ['{{', '}}'],
				views: __dirname + '/../views',

			});
			//console.log(readFileSync(__dirname + '/../views/incl/head.eta', {encoding:'utf8', flag:'r'}).toString());
			//eta.templates.define('head', eta.compile(readFileSync(__dirname + '/../views/incl/head.eta', {encoding:'utf8', flag:'r'}).toString(), {}));
			EtaSingleton.instance = eta;
		}

		return EtaSingleton.instance;
	}
}

export default EtaSingleton.getInstance();
```

Set as view engine for express in app.ts
```
app.engine('eta', etaInstance.__express);
app.set('view engine', 'eta');
```

and the controller looks like 
```
import expressAsyncHandler from 'express-async-handler';


export const index = expressAsyncHandler(async(req, res):Promise<void> => {
	res.render('index', {title: 'index'}); 
});
```

**Expected behavior**
The layout should contain the templateResult

**Screenshots**
<img width="2032" alt="screenshot" src="https://user-images.githubusercontent.com/97351820/235254968-8023f056-de65-4038-a302-f48aa02cff4d.png">

**Package & Environment Details**
 - Environment: NodeJS v19.9.0, tsc 5.0.4
 - Version: eta ^2.0.1

**Comment by nebrelbug** [comment]
You're forgetting to add the `=` sign to place data into the template ;).

So it should be `{{= it.title }}` and `{{= it.body }}` (or `{{~ it.body}}` if it's HTML)
