### ISSUE TITLE
Property 'render' does not exist on type 'typeof Eta'.

### ISSUE THREAD

**Issue by retorquere** [eta-dev/eta#234]
**Describe the bug**

Typescript compilation errors out with 

> Property 'render' does not exist on type 'typeof Eta'.

**To Reproduce**

run this typescript with ts-node (typescript 5.1.3):

```
import { Eta } from "eta";

const res = Eta.render('Hi, my name is <%= it.name %>', { name: "Ben" });
console.log(res); // Hi Ben!
```

**Expected behavior**

I expect this to run and output text to the console

**Screenshots**

![image](https://github.com/eta-dev/eta/assets/132108/8f0c2ff3-fb57-4513-89f1-165d91655375)

```
tt.ts:3:17 - error TS2339: Property 'render' does not exist on type 'typeof Eta'.

3 const res = Eta.render('Hi, my name is <%= it.name %>', { name: "Ben" });
```

**Package & Environment Details**

 - Environment: Node
 - Version: 19.8.1

**Comment by nebrelbug** [comment]
@retorquere thanks for submitting the issue! You need to initialize an instance of `Eta` first, then call `renderString` (not `render`) on that instance.

```js
import { Eta } from "eta";

const eta = new Eta()

const res = eta.renderString('Hi, my name is <%= it.name %>', { name: "Ben" });
console.log(res); // Hi Ben!
```

**Comment by retorquere** [comment]
I thought I saw the old syntax in the docs, but I can't find it now.

**Comment by nebrelbug** [comment]
@retorquere you probably did -- I had some troubles with publishing the new docs, so they weren't up to date when I released the package :sweat_smile:

**Comment by daredoes** [comment]
This happens to me while using the latest syntax as well
```Property 'renderString' does not exist on type 'Eta'.```

The following test never succeeds. 
```typescript
import {Eta} from 'eta';
describe('[class] TemplateEngine', () => {
  test('sets up as eta', () => {

    const eta = new Eta()

    const res = eta.renderString('Hi, my name is <%= it.name %>', { name: "Ben" });
    expect(res).toStrictEqual("Hi Ben!")
  });
})
```

Node Version: `v16.18.1`

**Comment by nebrelbug** [comment]
@daredoes you should probably change the last line's output :wink::

```js
expect(res).toStrictEqual("Hi, my name is Ben")
```

Where are you getting the error that `Property 'renderString' does not exist on type 'Eta'`?

**Comment by daredoes** [comment]
@nebrelbug it has something to do with my project's setup. I've gotten this to work by starting a project from scratch. 

The error occurs when running jest against that file

**Comment by CampaUTN** [comment]
I had the same problem as @daredoes. Setting typescript version to "5.1.3" did the job
