### ISSUE TITLE
Conditional `await includeAsync()` [v3.0.1]

### ISSUE THREAD

**Issue by Ningensei848** [eta-dev/eta#236]
**Describe the bug**

Conditional `await includeAsync()` on **Eta v3.0.1**

**To Reproduce**

```typescript
<%   if (it.flag){ %>
<%     const props = { childProps: it.children } %>
<%~    await includeAsync('./path-to-partial', props) %>
<%   } %>
```

**Expected behavior**

- Running without problems.

I think it is inconvenient that it stops working as soon as we put it in an `if` statement.
If it is not feasible (or difficult), I think it needs to be explicitly stated as such in the README.md.

**Screenshots**

Nothing.

**Package & Environment Details**

- Environment: Node
- Version: v18.16.0

**Additional context**

I use it to generate MDX (i.e. Markdown + JSX) instead of html. 
It is very comfortable to use and I recommend it to all my friends. 

Thank you very much.

**Comment by Ningensei848** [comment]
↑ 
Or perhaps it is not possible to include values that are not `it`-derived for props.

Is this additional view correct?
If so, would it be possible to insert the values afterwards ...... although that seems difficult ...... 😢

**Comment by Ningensei848** [comment]
@nebrelbug ,

Thanks for your reply. 

I must confess that the problem I have has been solved. 
Namely, I re-read the documentation and discovered that there is also an [`include()` function](https://eta.js.org/docs/intro/template-syntax#partials-and-layouts) implemented that works _synchronously_.

However, it remains unclear **why `await includeAsync()` does not work**. 
Is there a debug mode or something?

```typescript
const props = {
  entries: [
    { id_: "xxx" },
    { id_: "yyy" },
  ],
  records: [
    { id_: "xxx", results: [ { ... } ] },
  ]
}
```

```typescript
<% it.entries.forEach((entry) => { %>

<%   const { results } = it.records.find(({ id_ }) => id_ === entry.id_) %>

<% /* --------------------- NOT working --------------------- */ %>
<%   if (results.length > 0){ %>
<%~    await includeAsync('./result_table',  { results }) %>
<%   } %>
<% /* --------------------------------------------------------- */ %>

<% /* ------------------ Work as expected -------------------- */ %>
<%   if (results.length > 0){ %>
<%~   include('./result_table',  { results }) %>
<%   } %>
<% /* --------------------------------------------------------- */ %>

<% } %>
```

**Comment by nebrelbug** [comment]
@Ningensei848 I've tested locally and `await includeAsync()` is working for me. I'm guessing you're rendering your main template with `render` instead of `renderAsync`, which is required if any part of the template or partials is async.

**Comment by Ningensei848** [comment]
@nebrelbug ,

> await includeAsync() is working for me.

Is that true? So maybe something is going wrong in my environment ...?


> you're rendering your main template with `render` instead of `renderAsync`

I'm using `await renderAsync()` for rendering my templates. So I still think something is wrong with my environment...

---

On the other hand, there is no point in dwelling on it any longer, I think.

Now that I know that `include()` can be substituted, I will work through it as long as there is no significant difference in performance compared to `await includeAsync()`.


Thx for your patience up to this point.
If you have no problem with this response, I would appreciate it if you would close the issue.

Thank you very much 👍
