### ISSUE TITLE
[feature request] Add the `root` option as it was in v2

### ISSUE THREAD

**Issue by webdiscus** [eta-dev/eta#237]
**Is your feature request related to a problem? Please describe.**

Hallo @nebrelbug,

thanks for the new  cool version 3.
But v3 has many breaking changes and fails some very important options.

## Why the `root` option was deleted?

The `root` option is used in many templating engines, e.g. in `Ejs`. This option is the standard de facto.
For compatibility with the `v2.x` and `Ejs`-like templates, can you please return back the `root` options.
This option is really very ultra mega important.

**Comment by nebrelbug** [comment]
@webdiscus the `root` option is redundant in most cases. In some cases, it gives templates access to any file on your computer, which is generally bad practice. 

Why would you need this as opposed to `views`?

**Comment by webdiscus** [comment]
@nebrelbug 

yes, I think too that the `root` is redundant, and yes it is `bad practice`.

But, the `root` option is the `standard de facto` used in many most popular templating engines. Many project already have templates used `root` paths.

For a new project, this does not matter. But for many existing projects, this will be a very  hard breaking change. It will be a catastrophe.

Please keep the `standard` options at least `root` and `views` compatible with [`Ejs`](https://ejs.co/#docs). This is a serious big deal to stay loyal to Eta. 
`Don't shoot yourself in the foot` ;-)

**Comment by nebrelbug** [comment]
@webdiscus I've marked this release as version 3.0 because it is a breaking change (as are multiple other things in the API).

I feel like eliminating `root` is the best way for the project to move forward. Users who prefer to use `root` and `views` can continue using Eta.

**Comment by webdiscus** [comment]
@nebrelbug 

I don't use root paths myself, but for compatibility with the huge number of existing projects, it's best to keep this option.

A stable API is very important for Eta loyalty.
You can add new options or expand functionality, but never remove features that are already widely used, despite everything. 
"Legacy" features may slow things down, but should continue to work.

Thank you for your understanding.

**Comment by nebrelbug** [comment]
@webdiscus that's why this was released as a breaking change. Eta@2 still works well and can continue to be used. Users who wish to move forward without being burdened by legacy features can use Eta@3.

**Comment by webdiscus** [comment]
Then you should keep the documentation for v2.
But the page https://eta.js.org/docs/2.x.x/ is empty:
```
This is documentation for Eta 2.x.x, which is no longer actively maintained.
```

**Comment by nebrelbug** [comment]
@webdiscus the documentation still works and can be accessed through that link. It's not "actively maintained" because it's stable.
