### ISSUE TITLE
Add E variable in v3 as it was in v2

### ISSUE THREAD

**Issue by petercoppensdatylon** [eta-dev/eta#241]
Hello,

I had a template using V2, that sort of had this

```
const etaConfig = {
  async: true,
  autoEscape: false,
  views: __dirname + '/../reports',
  functions: {
    require: require
  },
};

....
const eta = new Eta(etaConfig);
....
eta.render(template, {})

```

And then I could use the following in the template

```
<%
mod = E.functions.require("....");
...

```
That no longer seems to work. I get an exception

ReferenceError: E is not defined

Is there some other way to access the configuration in the templates?

Tx!

Peter

**Comment by nebrelbug** [comment]
@petercoppensdatylon I love the creativity of this usage! I'd recommend something like the following.

First, extend the Eta class:

```js
const functions = {
	require: require
}

export class NewEta extends Eta {
  functions = functions;
}
```

Then create a new instance using `functionHeader`:

```js
const eta = new NewEta({ functionHeader: "const functions = this.functions" })
```

Inside your template, you'll then be able to write `functions.require("...")`.

Let me know how this works for you!

**Comment by petercoppensdatylon** [comment]
Hello,

Thanks for this tip. Really appreciate it. I first worked around it by passing in the functions through the render parameters, but I changed it using your suggestion. I like it better.

Best,

Peter
