### ISSUE TITLE
ETA cannot be rolled up into a web project due to 2 dependencies

### ISSUE THREAD

**Issue by daredoes** [eta-dev/eta#242]
**Describe the bug**
ETA is unable to be used in certain projects due to the usage of `node:fs` and `node:path`. 

**To Reproduce**
Build a library using RollupJS that uses Eta

**Expected behavior**
The library builds

**Screenshots**
<img width="1148" alt="image" src="https://github.com/eta-dev/eta/assets/6538753/ada2172e-c58c-4963-8ddd-2e9a4a3b72aa">

**Package & Environment Details**
 - Environment: Node
 - Version: ex. 16

**Additional context**
I was able to solve this in my own fork by completely removing the usage of `file-handler.ts`. It would be great to have `file-handler.ts` be its own package that can be added into Eta during the configuration.

**Comment by nebrelbug** [comment]
@daredoes try importing from `"eta/dist/browser.umd.js"` or `"eta/dist/browser.module.mjs"`.

**Comment by visoft** [comment]
I'm using deno in an edge function, and it doesn't have `node:fs` or `node:path`.

I'm seeing 
```
Failed to load module: "node:path" - Unsupported scheme "node" for module "node:path". Supported schemes: [
    "data",
    "blob",
    "file",
    "http",
    "https",
]
```

Right when I call `new Eta()`

**Comment by visoft** [comment]
I got around the issue by using:

`import { Eta } from "https://deno.land/x/eta@v3.0.3/src/core.ts";`

**Comment by nebrelbug** [comment]
@visoft I think the issue is your Deno version. Which are you using? It will likely need to be 1.31.0 or later.
