### ISSUE TITLE
Is it possible to remove '=' from left delimiter?

### ISSUE THREAD

**Issue by sanketdhoble** [eta-dev/eta#246]
Query-1:
I changed delimter to {{ }} with
```
eta.configure({
    tags: ['{{', '}}']
})
```

I still have to print variables using `my age is {{= it.age}}`. Is it possible to remove this `=` sign from delimter syntax? 

Query-2: 
Is it possible to remove 'it' for variable and directly print it like this `my age is {{age}}` instead?

Query-3:
eta throws error if `age` is not present in my nested source object when trying to access, `{{it.data.age.test}}`
Is there a way to overcome this?

**Comment by nebrelbug** [comment]
1. Pass in option `parse: {exec: "$", interpolate: "", raw: "~"}`. Note: to _run_ code, you'll have to prefix it with "$": `{{$ if(x) }}`
2. Yes, pass in option `useWith: true`
3. Use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining): `{{it.data?.age?.test}}`

**Comment by sanketdhoble** [comment]
@nebrelbug 
Optional chaining doesn't work with older node versions ( node 13 and below ).
I was wondering if there is way to do this via `eta` only similar to other templating tools like liquidJs, twigJs where by default it prints empty string if value is not accessible or undefined.

**Comment by nebrelbug** [comment]
@sanketdhoble sure, you can define an auto-filter function to do a try-catch around interpolations.

https://eta.js.org/docs/api#auto-filtering-data
