### ISSUE TITLE
Deno module cannot be found

### ISSUE THREAD

**Issue by matiasbattocchia** [eta-dev/eta#247]
Cannot download Eta package.

```
deno info https://deno.land/x/eta@v3.0.3/index.ts
error: module could not be found
```

Same command with other Deno modules works ok.

**Comment by nebrelbug** [comment]
@matiasbattocchia it should be https://deno.land/x/eta@v3.0.3/src/index.ts

**Comment by matiasbattocchia** [comment]
Thanks @nebrelbug. I missed it.
