### ISSUE TITLE
From V2 to V3 and from `includeFile` to `include`

### ISSUE THREAD

**Issue by yanna92yar** [eta-dev/eta#257]
Hi,
I was using `includeFile` fine, and along with global configuration `useWith: true`, I have been using:
```
|--index.eta
|--  includeFile('head.eta', it)

|--head.eta
|-- // variables inside `it` just work
|-- // it is well present and loaded in V3
```

Now `includeFile` bugs so I changed it to include, along with `useWith: true`, but variables are not being passed.

Adding `it.` to each variable will be painful :/ so better to find a better way

Thanks a lot ^^

**Comment by yanna92yar** [comment]
by the way everything suggested here does not work https://github.com/eta-dev/eta/issues/254

(passing destructed `{it}`, or an empty object `{}`)

**Comment by nebrelbug** [comment]
@yanna92yar you should be able to do `include('head.eta', it)`. Does that not work?

**Comment by yanna92yar** [comment]
No it doesnt, it was that way also before with includeFile

**Comment by nebrelbug** [comment]
@yanna92yar could you give me a minimal example?

**Comment by yanna92yar** [comment]
This is an example: https://github.com/yanna92yar/test-eta

Thanks a lot ^^

**Comment by nebrelbug** [comment]
You need to pass the config directly into the `Eta()` constructor. In your repo,

```js
  engine: {
    eta: new Eta.Eta({ useWith: true })
  },
```

**Comment by yanna92yar** [comment]
Thanks a lot 🙏
