### ISSUE TITLE
Cannot use Node ESM because `es` version contains `requires` / wrong extension for ES version

### ISSUE THREAD

**Issue by talentlessguy** [eta-dev/eta#26]
**Describe the bug**

When trying to import a module in a Node ESM file, it crashes. I tried making a hotfix, but it crashed due to another reason.

**To Reproduce**
1. Create a npm project and `index.mjs` file
2. Try to import: `import eta from 'eta'`
3. See this:

```js
export { renderFile as __express, compile, compileToString, config, configure, config as defaultConfig, getConfig, loadFile, parse, render, renderFile, templates };
^^^^^^

SyntaxError: Unexpected token 'export'
```

then I also tried:

3. Go to `node_modules/eta/package.json` and append `"type": "module"`
4. See this:

```
file:///home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/eta@1.10.0/node_modules/eta/dist/eta.es.js:586
var fs = require('fs');
         ^

ReferenceError: require is not defined
    at file:///home/v1rtl/Coding/tinyhttp/node_modules/.pnpm/eta@1.10.0/node_modules/eta/dist/eta.es.js:586:10
```

**Expected behavior**

It should have been resolved using any of the Node resolution strategies.

**Package & Environment Details**
 - Environment: Node 14.11, Manjaro Linux x64
 - Version: 1.10.0

**Additional context**

There are different ways to make this work. The first one is fixing the build to avoid calling `require` in ES versions of builds and putting `"type": "module"` in package.json. Another way is to change the extension of es version to `.mjs`.

**Comment by nebrelbug** [comment]
Hey @talentlessguy, thanks for reporting this!

I'm unfortunately going to be away from the internet from now until tomorrow evening, but I'll try to fix and release then.

**Comment by nebrelbug** [comment]
@talentlessguy just fixed and released: https://github.com/eta-dev/eta/releases/tag/v1.10.1.

Let me know if this works or you have any other issues!

**Comment by talentlessguy** [comment]
> @talentlessguy just fixed and released: https://github.com/eta-dev/eta/releases/tag/v1.10.1.
> 
> Let me know if this works or you have any other issues!

Looks like it's working nicely, thanks for taking time to fix this!
