### ISSUE TITLE
[Question] How to trim newline depending on condition?

### ISSUE THREAD

**Issue by tjhoo** [eta-dev/eta#260]
Hi,
When handling multiple member names using the following template,
```
<% it.members.forEach(function (member, index) { %>
  <%= member.name -%>
  <% if (index < it.member.length - 1) { %>
    <p>&nbsp;&amp;</p>
  <% } %>
<% }) %>
```
the above will produce
```
JOHN WOO
&
MIKA HAKKINEN
&
ALICE
```
How can I make it to output something like this?
```
JOHN WOO &
MIKA HAKKINEN &
ALICE
```
It looks like I should use something described [here](https://eta.js.org/docs/intro/template-syntax#whitespace-control)? Unfortunately I couldn't make it works. Maybe more examples of how to trim whitespaces and newlines will be helpful.

**Comment by nebrelbug** [comment]
I'm guessing the problem is with your HTML, not the template? Typically <p> tags display on a new line.

This template:
```ejs
<% it.members = [{name: "John Woo"}, {name: "Mika Hakkinen"}, {name: "Alice"}] %>

<% it.members.forEach(function (member, index) { %>
<%= member.name -%>
<% if (index < it.members.length - 1) { %>
  <p>&nbsp;&amp;</p>
<% } %>
<% }) %>
```

Produces this output for me:
```ejs

John Woo  <p>&nbsp;&amp;</p>
Mika Hakkinen  <p>&nbsp;&amp;</p>
Alice
```

(You can test it out on https://eta.js.org/playground)

**Comment by tjhoo** [comment]
@nebrelbug Thanks for your explanation. It is indeed a problem in my HTML.

To conclude this issue, here is how I fixed the HTML using inline-block `span` to achieve what I wanted

```
<% it.members = [{name: "John Woo"}, {name: "Mika Hakkinen"}, {name: "Alice"}] %>
<% it.members.forEach(function (member, index) { %>
  <p><%= member.name %>
  <% if (index < it.members.length - 1) { %>
    <span>&nbsp;&amp;</span>
  <% } %>
  </p>
<% }) %>
```
