### ISSUE TITLE
with statement is deprecated by web standards.

### ISSUE THREAD

**Issue by AimForNaN** [eta-dev/eta#271]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with

This makes `eta` no longer useful for long-term projects.

**Comment by nebrelbug** [comment]
@AimForNaN `eta` doesn't use `with` unless you explicitly enable a flag that's turned off by default.

**Comment by AimForNaN** [comment]
That's something that I would enable, since I'm not a fan of prefixing template vars.
