### ISSUE TITLE
Pass entire it context under partial

### ISSUE THREAD

**Issue by multivoltage** [eta-dev/eta#272]
## description request
I need to get `myVar` from `it` context in a templated called by parent with `<%~ include("./footer", { it: allEntireIt }) %>`
and use inside footer `<%~ it.myVar %>`

## proposal solution
Pass entire all contex down the three

## alternative
Maybe this is not a feature and there is already a method for this goal

**Comment by multivoltage** [comment]
@nebrelbug 
I think solution is
```js
<%~ include("./footer", { ...it }) %>
```
Maybe I can open a PR for improve docs? Probably for you and people using template engine is "easy" to imaginate spread operator, but for me I spent 1 entire day :)

**Comment by nebrelbug** [comment]
@multivoltage glad you got it working! Another possibility is 

```ejs
<%~ include("./footer", it) %>
```

I'd appreciate a PR!
