### ISSUE TITLE
Interpolation of an unset value prints "undefined"

### ISSUE THREAD

**Issue by AntonNech** [eta-dev/eta#28]
Hello.
While trying to implement value prefilling for my inputs I encountered many "undefined" values for unset variables.

Steps to reproduce:
1. Go to interactive examples https://eta.js.org/docs/examples/interactive
2. Change `Eta.render('Hi <%= it.name %>', {name: 'Person'})` to `Eta.render('Hi <%= it.name %>', {})`
3. Press Run button. Result is "Hi undefined".

It is very inconvenient to use something like <%= it.name || "" %> for each interpolation especially for input prefilling. So I think showing "" instead of "undefined" is more correct.
EJS thinks the same way and renders "Hi " if I modify this example for it.
However if it is intended and there is another way to interpolate undefined values as "" please add it to the documentation.

**Comment by nebrelbug** [comment]
Hey @AntonNech,

Thanks for the great question! Currently this isn't possible out-of-the-box with Eta.

This would be relatively easy to implement either as a plugin or as a built-in part of Eta, and I'm not sure which is better.

I want to keep Eta's bundle size down, but I also want to simplify usage of Eta. The trick is balancing those two goals :wink:

**Comment by willemmulder** [comment]
We could maybe make it a config option what eta should render for undefined values? I feel it's core behaviour, but would be good to keep things flexible?

**Comment by nebrelbug** [comment]
After thinking about this, my thought is that the best solution would be creating a `filter` configuration option. This could solve @AntonNech's use case:

```js
eta.configure({
  filter: function (val) {
    return (val === undefined || val === null)? "": val
  }
})
```

As well as allowing for other more complex examples:

```js
eta.configure({
  filter: function (val) {
    if (censored.includes(val)) {
      return "@#$%@"
    } else {
      return val
    }
  }
})
```

Any thoughts?

**Comment by willemmulder** [comment]
Yes, even better! Good thinking 👍

**Comment by AntonNech** [comment]
@nebrelbug Any solution that enables possibility of printing an empty space instead of "undefined" would be appreciated.
This filter configuration option seems good and flexible solution, capable of solving some other possible issues.

**Comment by nebrelbug** [comment]
@AntonNech just published https://github.com/eta-dev/eta/releases/tag/v1.11.0, with filter support!

I haven't documented it yet, but you should be able to use it like in the example above: 

```js
eta.configure({
  filter: function (val) {
    return (val === undefined || val === null)? "": val
  }
})
```

**Comment by AntonNech** [comment]
Thank you! Everything works great, no more "undefined".
