### ISSUE TITLE
renderStringAsync not working in Angular 17

### ISSUE THREAD

**Issue by vjm14** [eta-dev/eta#286]
**Describe the bug**
We are trying to use renderStringAsync function to execute a custom function with an await, but we always get an error. 

We are using Angular 17.

**To Reproduce**
```typescript
const eta = new Eta({
                autoEscape: false,
                tags: ["{{", "}}"],
                varName: 'listOf',
                useWith: true
});

const result = eta.renderStringAsync(`Hello {{= await  hello(test1) }} \n\n {{= await world(test2) }}`, {
          test1: "hello",
          test2: "world",
          hello: (e) => Promise.resolve(e),
          world: (e) => Promise.resolve(e)
})
```

**Error encountered:**
![error](https://github.com/eta-dev/eta/assets/129290424/168d1c53-f79a-45e4-a0b6-639e22ad074a)

**Expected behavior**
Expecting to behave the same in the documentation.
![image](https://github.com/eta-dev/eta/assets/129290424/8cbbdf89-2adf-47b2-af05-7cdfa2afa930)

**Package & Environment Details**
 - Environment: Node version 20.10.0
 - ETA Version: 3.4.0
 - ES build
 - Angular CLI: 17.0.10
 - Package Manager: npm 10.2.3
 - OS: win32 x64

**Comment by nebrelbug** [comment]
@vjm14 hmm, this is a bit confusing. It's working when I try your code in a clean environment. Could it be something about Angular?

See https://runkit.com/embed/vlwyx6jco93r

**Comment by vjm14** [comment]
@nebrelbug Thank you for taking a look. We are currently using the squirrelly and we are just migrating to ETA. In squirrelly we have no issues when running the async await function in angular, but in ETA we can't run it without an error.

**Comment by vjm14** [comment]
@nebrelbug We tried to debug the ETA and this is what we see. Since async is set to true, the "ctor" is being set as a Function. not as a AsyncFunction.  Do you have any suggestions or alternatives that i can do?
![MicrosoftTeams-image (3)](https://github.com/eta-dev/eta/assets/129290424/d53f1f3c-5cc4-4d2c-9b3b-fef235a1ac13)

**Comment by vjm14** [comment]
@nebrelbug I think we resolve the issue. We tried to copy the AsyncFunction in squirrelly and replace it in the ETA and it works. We don't get the error anymore.

```
ETA:
 const AsyncFunction = async function () {}.constructor;

Squirrelly:
const AsyncFunction = new Function('return (async function(){}).constructor')();
```

**Comment by nebrelbug** [comment]
@vjm14 glad to hear you solved it! I'm guessing it has to do with some perplexity of Angular's execution environment, where async works in one context but not in another. I'll close this as resolved, since I don't think this is a common issue.
