### ISSUE TITLE
Is it possible to use eta.js in minified state?

### ISSUE THREAD

**Issue by serge-starynets** [eta-dev/eta#287]
Hello,

Is it possible to minify eta.js code and use it?
As example, I have some js evaluator tool which accepts js code as string and runs it. For now it is possible to integrate minified version of another template library - I just add minified library code to the user provided code before run. So can I do the same with eta.js?

Thanks!

**Comment by nebrelbug** [comment]
I'm not quite sure what you're trying to do. Eta is already released as a minified bundle.

**Comment by serge-starynets** [comment]
So basically I want eta.js be available inside isolated-vm library runtime. I'm concatenating minified eta.js code with some JS code and pass it to the isolated-vm eval function. This approach worked well with another templating library, but eta.js is more powerful and I'm wondering if it's even possible.

So far I'm getting `Eta is not defined` error when try to run code with described approach.

I know that eta.js minified bundle works in browser's environment, but maybe it's not true for Nodejs?

**Comment by serge-starynets** [comment]
@nebrelbug  Yes but I minified it and I think that's was the issue. I tried without minification and the error gone now. Thanks for the hint!

**Comment by nebrelbug** [comment]
@serge-starynets glad that the issue was resolved!
