### ISSUE TITLE
"EtaConfig" is not exported in JSR

### ISSUE THREAD

**Issue by pasha-bolokhov** [eta-dev/eta#295]
While you can do 
```typescript
import type { EtaConfig } from "https://deno.land/x/eta@v3.4.0/src/config.ts";
```

you can't do
```typescript
import type { EtaConfig } from "jsr:@eta-dev/eta@3.4.0"
```

because it is not being currently exported…

Please export it

**Comment by nebrelbug** [comment]
Good catch! I don't have time for a fix atm but I'd be happy to merge a PR!

**Comment by pasha-bolokhov** [comment]
works now in 3.5.0 after the merge, thanks!
