### ISSUE TITLE
Denopack Bundling For Deno Dependencies

### ISSUE THREAD

**Issue by shadowtime2000** [eta-dev/eta#33]
**Is your feature request related to a problem? Please describe.**
No it is not.

**Describe the solution you'd like**
1. The exporting of dependencies from `file-methods.deno.ts` to only export what is actually used in `file-utils.ts`
2. Using `denopack` to bundle `file-methods.ts` in the `deno_dist` with tree shaking so you only use what is needed keeping the total size of files loaded low.

**Describe alternatives you've considered**
`deno bundle` but that doesn't support tree shaking.

**Comment by nebrelbug** [comment]
This is a really interesting idea!

Do you know if this would increase the file size a lot? Also, how easily would this integrate into the current build process?

My initial feeling is that it would be best to keep `file-methods.ts` minimal so it just imported the `std` modules, which would likely be cached on the user's device. I'm open to persuasion though :smiley:

**Comment by shadowtime2000** [comment]
I am going to close this as it has been a while and I think I am going to drop this idea on my own.
