### ISSUE TITLE
Know The Codebase Contributing

### ISSUE THREAD

**Issue by shadowtime2000** [eta-dev/eta#38]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A "Know the Codebase" section in the `CONTRIBUTING.md`

**Describe alternatives you've considered**
None.

**Comment by LeanKhan** [comment]
Hi @shadowtime2000 long time, I would like to contribute to this. Can you point me in the right direction?

**Comment by shadowtime2000** [comment]
@LeanKhan Hi! It would be wonderful to have someone contribute to this. To be honest, I don't know if there really is a right direction here to understanding the codebase. Though, really I would say you could learn how exactly everything connects with each other just by starting at `index.ts` and moving from there, the amount of time it would probably take would be suboptimal, but honestly I can't think of a better way to know a codebase than to just get deep into it.

**Comment by nebrelbug** [comment]
Closing this as stale.
