### ISSUE TITLE
How to add a plugin?

### ISSUE THREAD

**Issue by dflorey** [eta-dev/eta#4]
I'm just getting started with Eta and struggle to find an example how to plugin a custom function e.g. to add IntlMessageFormat.
Is there some context in Eta or do I have to provide all functions on window level?

**Comment by nebrelbug** [comment]
Hi @dflorey, sorry for the late response! I'm just starting at a new job and am struggling to stay on top of everything :)

The simplest way to do what you're describing would probably just be to pass the function in the data object. You could also define it as a filter or a helper.

You could also write a plugin that would modify the source of the generated template function, but I think the other options would be significantly simpler.

Let me know if you have questions about or would like examples of any of these options!
