### ISSUE TITLE
Create linter for Eta templates

### ISSUE THREAD

**Issue by nebrelbug** [eta-dev/eta#42]
We should create a linter for Eta templates, similar to https://github.com/RyanZim/EJS-Lint. This would be very useful for checking the validity of Eta templates -- Eta, like EJS, uses `new Function()` to generate compiled template functions, and `new Function()` doesn't throw detailed syntax errors.

> EJS-Lint replaces everything outside a scriptlet tag with whitespace (to retain line & column numbers) and then runs the resulting (hopefully) valid JS through [node-syntax-error](https://github.com/browserify/syntax-error) to check for errors.

We probably want to do something similar to this, but use a modified version of [Eta's parser](https://github.com/eta-dev/eta/blob/master/src/parse.ts) to handle multi-line comments and strings correctly. 

Ideally the linter would be available as an [Eta plugin](https://eta.js.org/docs/learn/plugins) using the `processTemplate` hook and as a command-line tool.

**Comment by shadowtime2000** [comment]
I could try this.

**Comment by nebrelbug** [comment]
@shadowtime2000 that would be fantastic!

**Comment by shadowtime2000** [comment]
@nebrelbug Do you think maybe we should make it so it runs it through ESLint if users want so?

**Comment by nebrelbug** [comment]
@shadowtime2000 that would be super cool!

It would probably have to take into account that certain variables are predefined (like `tR`, `layout`, `it`, etc.)

Also, that the user can use the `useWith` option.

**Comment by nebrelbug** [comment]
One possible solution would be to wrap the template in `function (it, E, cb) { var tR='',...` and then adjust error line and column numbers accordingly

**Comment by shadowtime2000** [comment]
We could also just create an `eslint-plugin-eta` with an `eta` processor.

**Comment by shadowtime2000** [comment]
I think we should leave it up to the user to add the various `eta` related globals to the `ESLint` globals field.

**Comment by shadowtime2000** [comment]
@nebrelbug I completed a working ESLint plugin to lint Eta templates. I feel like it should be put on Github under the `eta-dev` organization to keep it centralized. Thoughts?

**Comment by nebrelbug** [comment]
@shadowtime2000 that's great! 

I agree that would probably be best. Since I added you to the `eta-dev` team, you should be able to create a new repo. Let me know once it's published!

**Comment by shadowtime2000** [comment]
@nebrelbug Done!

Should we close this issue then?

**Comment by shadowtime2000** [comment]
Also, I am not the best at READMEs, so it probably needs a cleanup.

**Comment by nebrelbug** [comment]
@shadowtime2000 sweet! I'll close it now.

I'll look over the README tomorrow :)
