### ISSUE TITLE
Sharing ESLint Config

### ISSUE THREAD

**Issue by shadowtime2000** [eta-dev/eta#43]
**Is your feature request related to a problem? Please describe.**
No, not really.

**Describe the solution you'd like**
The ESLint config to be shared on NPM with a name like `eslint-config-eta-dev`.

**Describe alternatives you've considered**
Copy and pasting the config everywhere.

**Additional context**
The reason I am suggesting this is so it is easy to lint projects relating to this (integrations).

**Comment by nebrelbug** [comment]
I like this idea. To reduce the number of packages to maintain, though, we could just export a config from `eslint-plugin-eta`. Thoughts?

**Comment by shadowtime2000** [comment]
> I like this idea. To reduce the number of packages to maintain, though, we could just export a config from `eslint-plugin-eta`. Thoughts?

@nebrelbug I believe that exporting configs from a plugin is meant for when those configs actually change the rules that the plugin provides, but currently, the plugin does not provide any rules. I am fine with doing it, but I don't think that is the use case.

**Comment by nebrelbug** [comment]
@shadowtime2000 okay, let's create a separate package called `eslint-config-eta` then

**Comment by shadowtime2000** [comment]
@nebrelbug Do you want to move it and publish it, or should I?

**Comment by nebrelbug** [comment]
Closed by #45
