### ISSUE TITLE
Official Command Line Tool

### ISSUE THREAD

**Issue by shadowtime2000** [eta-dev/eta#44]
**Is your feature request related to a problem? Please describe.**
There is no official CLI for `eta`.

**Describe the solution you'd like**
A CLI preferably written in Typescript using [yargs](https://github.com/yargs/yargs). It should be able to facilitate testing to make sure it is working properly.

**Describe alternatives you've considered**
Not having a CLI.

**Additional context**
I could work on this, I just want to see what people think.

**Comment by shadowtime2000** [comment]
@nebrelbug Thoughts?

**Comment by nebrelbug** [comment]
This is a great idea!

We should look at https://github.com/mde/ejs and https://github.com/pugjs/pug-cli for some examples of similar tools.

Ideally a CLI would accept configuration options through command line flags or through a config file like `eta.config.js` (maybe `eta-vscode` could use the same file?)

We'd need to think about how we'd handle partials and layouts.

**Comment by shadowtime2000** [comment]
I was thinking it would do the prerendering of templates and then add the ability to render templates.

**Comment by shadowtime2000** [comment]
Also, should we keep the CLI within this `eta` package or a new package such as `etajs-cli` (`eta-cli`) is already taken.

**Comment by shadowtime2000** [comment]
Just as a side note, it could also seem like a good idea to use a framework like [oclif](https://oclif.io). It may add a little bit of structure.

**Comment by shadowtime2000** [comment]
@nebrelbug I think oclif is more built and structured for the CLI to be in its own package because of the complexity of it and how it may interfere with the current `package.json` build and other processes. I would prefer to just use `yargs` because it is simple but also testable. I think it is a more popular practice to keep the CLI code in a folder called `/bin`.

**Comment by nebrelbug** [comment]
@shadowtime2000 my bad, `/bin` is better :smiley:

I think either option -- `yargs` in the main repo or `oclif` in a separate repo -- would be great.

**Comment by shadowtime2000** [comment]
@nebrelbug We could also just use `yargs` in a separate repo because it is a little simpler and user to test. I am going to start working on that but if you think that should change feel free to tell me 😃

**Comment by shadowtime2000** [comment]
I completed the CLI with basic compiling functionality and I have unit tests with Jest. Now I think it is time to decide the package name. Since `eta-cli` is taken the name I am using rn is `etajs-cli`. Any suggestions?

**Comment by nebrelbug** [comment]
@shadowtime2000 great! `etajs-cli` sounds good to me; I'm thinking we should just have the script called `eta`.

**Comment by shadowtime2000** [comment]
I am going to close this now because the CLI has been published.
