### ISSUE TITLE
Add documentation for webpack

### ISSUE THREAD

**Issue by clshortfuse** [eta-dev/eta#46]
**Describe the solution you'd like**
Add some sort of documentation somewhere that explains how to integrate with webpack.

**Additional context**

It works perfectly fine with `html-loader` if you want to compile to `.html` (eg: use as HTML preprocessor instead of during runtime). This is what I'm using at the moment:

````js
{
  loader: 'html-loader',
  options: {
    preprocessor(content, loaderContext) {
      return eta.render(content, {}, { filename: loaderContext.resourcePath });
    },
  },
}
````

This is more to serve as a guidance for others trying to figure out how to integrate with `eta`.

**Comment by shadowtime2000** [comment]
Your current configuration seems good and I will add it to the documentation, but it may be better to just create an `eta-loader` so it can precompile into a function instead of render.
