### ISSUE TITLE
Syntactic Sugar : renderAsync

### ISSUE THREAD

**Issue by calumk** [eta-dev/eta#49]
**Is your feature request related to a problem? Please describe.**
`async:true` feels a little clunky, when added as an additional parameter for `Eta.render()`

```
let result = await Eta.render(
  '<%= it.name %>: <%= await it.asyncFunc() %>',
  { name: 'Ada Lovelace', asyncFunc: asyncFunc },
  { async: true }
)
```

**Describe the solution you'd like**
Could we have an additional function `Eta.renderAsync()`

```
let result = await Eta.renderAsync(
  '<%= it.name %>: <%= await it.asyncFunc() %>',
  { name: 'Ada Lovelace', asyncFunc: asyncFunc }
)
```

I think this would improve legibility.

**Comment by shadowtime2000** [comment]
Hi,
This seems like a good idea, I think this could make it more compatible with the [JSTransformer](https://www.npmjs.com/package/jstransformer) template engine standard. Would you be interested in contributing this @calumk?

**Comment by shadowtime2000** [comment]
Along with `renderAsync` we could also do a `renderFileAsync` function.

**Comment by calumk** [comment]
Both would be appreciated 👍

**Comment by shadowtime2000** [comment]
@all-contributors please add @calumk for ideas
