### ISSUE TITLE
configuration options

### ISSUE THREAD

**Issue by nateleavitt** [eta-dev/eta#6]
Have been trying to configure the Eta `varName` config options, but am having issues with it.

Based on the limited docs on config options, I've ended up with the following:

```
let compiled = Eta.compile(html)
compiled(userOptions, Eta.getConfig({varName: 'user'}))
```
But I am getting the following error:

```
ReferenceError: user is not defined
```

What am I missing?

**Comment by nebrelbug** [comment]
Hi @nateleavitt, sorry for the late reply! Would you mind giving an example of a template that errors? Thanks!

**Comment by nebrelbug** [comment]
@nateleavitt I'll close this for now. `varName` is working in my local tests. Feel free to re-open this if you have any more issues.
