### ISSUE TITLE
eta-vscode cannot install in wsl ubuntu

### ISSUE THREAD

**Issue by ndzeux** [eta-dev/eta#66]
How to install eta-vscode extension in wsl, I can only install it locally

**Comment by shadowtime2000** [comment]
@ndzeux [eta-vscode](https://github.com/shadowtime2000/eta-vscode) is not actually part of the `eta-dev` Github organization. I have just added a link to the VSCode marketplace page for `eta-vscode`, sorry I forgot to put the link in the repo. I don't have much experience with WSL Ubuntu, you should be able to download it from the marketplace. I am going to close this, if that doesn't work please open it in the `shadowtime2000/eta-vscode` repo instead.
