### ISSUE TITLE
Get undefined from it.body

### ISSUE THREAD

**Issue by triasbrata** [eta-dev/eta#77]
**Describe the bug**
i try follow this example and get strange  "undefined" https://eta.js.org/docs/learn/layouts 

**To Reproduce**
just copy paste from example Simple Layout from  https://eta.js.org/docs/learn/layouts 

**Screenshots**
![image](https://user-images.githubusercontent.com/4735597/103864301-4d5fbd00-50fd-11eb-8e87-72a8cc18281d.png)

**Comment by shadowtime2000** [comment]
@triasbrata Can you share the code for actually doing the rendering of it?

**Comment by triasbrata** [comment]
My code is wrong, when I call layout I use `<%~ %>` and when I change it only use `<%%>` the undefined is gone

sorry for my english
