### ISSUE TITLE
Provide full path to current parsing ETA template in process.env

### ISSUE THREAD

**Issue by js2me** [eta-dev/eta#79]
Hello!   
Firstly, thanks for this powerful tool!   

I use ETA template in https://github.com/acacode/swagger-typescript-api   
And currently I have a problem with using custom `require()` function inside ETA template   

`__dirname` contains path where placed custom `required()` function   
`process.cwd()` contains path to direction of the called script which use ETA templates  

Custom raw implementation of `require()` function   
```js
require = (packageOrPath) => {
    const isPath = _.startsWith(packageOrPath, "./") || _.startsWith(packageOrPath, "../");

    if (isPath) {
      return require(path.resolve(process.cwd(), packageOrPath))
    }

    return require(packageOrPath);
  }
```    

Thanks!

**Comment by shadowtime2000** [comment]
@js2me Sorry for taking so long to respond, but what exactly is the problem with this basic require function? Can you clarify on what exactly is the question you are asking?

**Comment by js2me** [comment]
Hello @shadowtime2000   
I need a `require()` function in ETA templates which works like `require()` in NodeJS  
Or provide the ability to get path to current parsing template as NodeJS environment variable

**Comment by js2me** [comment]
Just I want to use require() in ETA templates   
like  
```ejs
Hello <%~ require("./currentUser") %>  
```
