### ISSUE TITLE
Question: VSC support for .eta

### ISSUE THREAD

**Issue by RaknaXTR** [eta-dev/eta#8]
There's an VSC extension for .eta?

**Comment by nebrelbug** [comment]
Not yet, but extensions for EJS should work just fine for most things except custom delimiters.

Hopefully someone will make one soon--it shouldn't be too hard to create. They would just need to fork one of the EJS extensions and tweak it to use Eta's syntax

**Comment by shadowtime2000** [comment]
@RaknaXTR I created the [eta-vscode](https://marketplace.visualstudio.com/items?itemName=shadowtime2000.eta-vscode) extension. Hope that helps!
