### ISSUE TITLE
Benchmarks Don't work

### ISSUE THREAD

**Issue by David-Carty** [eta-dev/eta#81]
Benchmarks are failing.  Go here:

https://ghcdn.rawgit.org/eta-dev/eta/master/browser-tests/benchmark.html

Results in: 

429: Too Many Requests

Maybe misleading, could be a CORS issue try adding an Access-Control-Allow-Origin header

Raised as performance is obviously a big motivator to use eta.

**Comment by shadowtime2000** [comment]
Yeah, I am not able to figure out why. I think I will try to find another Github CDN to use or maybe I will use a hosting service to statically host those files.

**Comment by David-Carty** [comment]
It will be worth the effort.  Eta is number 1 on my shortlist.  I need to do a little more research but it certainly looks good. All the best. D.
