### ISSUE TITLE
Security Contact Needed #217

### ISSUE THREAD

**Issue by agustingianni** [eta-dev/eta#82]
Hello,

I am a member of the GitHub Security Lab (https://securitylab.github.com).

I've attempted to reach a maintainer for this project to report a potential security issue but have been unable to verify the report was received. Please could a project maintainer contact us at securitylab@github.com, or provide an email address so we can contact you.

Thank you,
Agustin Gianni (@agustingianni)
GitHub Security Lab

**Comment by shadowtime2000** [comment]
Thanks for letting me know @agustingianni,

I am assuming when you contacted a maintainer you contacted @nebrelbug who is away on a 2 yr leave. I have emailed `securitylab@github.com` to get the details about this.

**Comment by agustingianni** [comment]
Thank you very much, yes I did mail @nebrelbug so instead now I will get in contact with you through that email address. Thank you again.
