### ISSUE TITLE
Great Error Reporting.

### ISSUE THREAD

**Issue by damiantoczek** [eta-dev/eta#86]
Issue here is that it doesn't have a good error reporting.
It works on my localhost but it doesn't work when deployed and the only thing i see is this error here:

```Bad template syntax

Unexpected token '.'```

I don't know why you call it a great error reporting. 
I have 92 dots in my template...

**Comment by shadowtime2000** [comment]
@damiantoczek Can you share the template that is being used?

**Comment by damiantoczek** [comment]
> @damiantoczek Can you share the template that is being used?

Turned out to be a DigitalOceans fault.
https://github.com/eta-dev/eta/discussions/88

**Comment by shadowtime2000** [comment]
@damiantoczek I think I will close this then.
