### ISSUE TITLE
How to render a template from a file/folder?

### ISSUE THREAD

**Issue by willemmulder** [eta-dev/eta#9]
Hi, I'm new to eta, and I'm looking at the documentation.

My goal is to render templates in NodeJS from a 'templates' folder that would contain a set of templates, e.g. 'main.html' and 'footer.html'.

I do see something about templates here https://eta.js.org/docs/api/configuration but it is not clear in the docs where to actually pass those config options, and there is also no example on how to render a template from a file. 

Could you add that to the docs? Thanks!

**Comment by nebrelbug** [comment]
Hi @willemmulder, I'll definitely add that to the docs!

Here's how you can do it in the meantime:

```js
// The path to the template is relative to the JS file executing
eta.renderFile("./path-to-template.eta", { data })

// This returns a promise but can also accept a callback, so the following both work:

async function renderTemplate() {
 	let rendered = await eta.renderFile("./template.eta", myData)
}

eta.renderFile("./template.eta", myData, function (err, rendered) {
	console.log(rendered)
}
```

Hope this helps! Let me know if you have any questions.

**Comment by willemmulder** [comment]
Thanks, that works! 

Quick follow-up: where can I set/adjust these config values? https://eta.js.org/docs/api/configuration

The main thing is that I want eta to cache the template-compilation automatically, whenever I use renderFile(...).

**Comment by nebrelbug** [comment]
@willemmulder there are a few options. The first is that you could change `Eta.defaultConfig`:

`Eta.defaultConfig.cache = true`

`renderFile` also allows you to override configuration right from the data object:

```js
eta.renderFile("./template.eta", {...myData, cache: true}, function (err, rendered) {
	console.log(rendered)
}
```

**Comment by willemmulder** [comment]
Thanks, great!

One suggestion: wouldn't it be better to not mix the data object and configuration options together? That could cause to unpredictable behaviour when I intend to use a specific variablename, but instead eta would set a configuration value. We could maybe move the config values to a separate parameter, like

```
eta.renderFile("./template.eta", {...myData}, {cache: true}, function (err, rendered) {
	console.log(rendered)
}
```

**Comment by nebrelbug** [comment]
@willemmulder I definitely think that would be more intuitive. The problem is that right now `renderFile` is aliased as `__express`, a helper function to make Eta work with Express.js out-of-the-box, and Express expects it to have the signature above.

I've been meaning to do some rewriting of Eta's file handling anyway. Perhaps I should make `__express` a wrapper function that calls `renderFile`, and update `renderFile` to have a more intuitive/useful configuration manager.

The one potential problem is backwards compatibility -- don't want to break Eta for anyone, but I'd also rather not release a new major version. I don't think many projects use `renderFile`, but I'd have to try to find those that do and notify them the API changed.

Any suggestions? Thanks for your great feedback!

**Comment by willemmulder** [comment]
@nebrelbug That would be great!

You don't have to break anything as long as you keep support for the 'old style' (i.e. mixed data and config object) as well. You could check the amount of arguments to determine if the function is called the old or the new way, right? If it is string-obj-obj-function then it's new, if it's string-obj-function then it's old. And then map properly internally.

However that would not solve the problem that express expects the above signature. Because we'd have to merge input objects there anyway, causing the same trouble as before. What express function are you calling?

And I just checked: EJS is also using a separate 'options' object. See https://ejs.co/#docs

**Comment by nebrelbug** [comment]
@willemmulder in version `1.3.0` I just added support for both kinds of function signature! This means you can now do:

```js
eta.renderFile("./template.eta", {...myData, cache: true}, function (err, rendered) {
	console.log(rendered)
}
```

Or

```js
eta.renderFile("./template.eta", myData, {cache: true}, function (err, rendered) {
	console.log(rendered)
}
```

**Comment by nebrelbug** [comment]
As far as the Express function, I based the signature on https://expressjs.com/en/4x/api.html#app.engine

**Comment by willemmulder** [comment]
Perfect!

I didn't know that Express supported rendering engines out of the box. Nice! I use Koa anyway, but good to know.
Did you try to get eta added to this list: https://github.com/expressjs/express/wiki#template-engines ? Would be good for exposure 👍 

Issue closed by the way!

**Comment by nebrelbug** [comment]
Thanks! I got Eta added to https://expressjs.com/en/resources/template-engines.html. The wiki is supposed to be deprecated, but it doesn't look like they've moved on that :grimacing: and so a lot of people are probably still seeing the outdated list.

Maybe I'll suggest that they replace the Wiki list with a link to the website page.

**Comment by willemmulder** [comment]
Yes that would be good; but even then Google will bring some people to the wiki anyway, so it wouldn't hurt adding eta on the wiki as well.
